# Kinship Library
## Notebook 01: Collection, Data Quality and Exploratory Analysis

### Goal

Build a trustworthy thematic book catalogue before modeling.

This notebook covers the useful work from the original Day 1 and Day 2.

### Main project question

Can book descriptions and subject metadata help readers discover meaningful books about living in connection with self, community, nature, and ancestral knowledge?

### Data principles

We keep source metadata separate from our later reader paths.

We do not assume that Yoga, Ayurveda, Indian spirituality, Kogi knowledge, Muisca knowledge, and ecological philosophy are interchangeable.

We keep the source and search query for every record so that the collection process remains traceable.

### Outputs

`data/raw/open_library_books.csv`

`data/raw/books_to_scrape.csv`

`data/processed/books_clean.csv`

## 1. Setup

### Purpose

Import simple libraries and define repository relative paths.

### Expected result

The folders are created automatically. The same notebook can run in Colab or from a cloned repository.

In [12]:
from pathlib import Path
from google.colab import drive

drive.mount("/content/drive")

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/kinship_library"
)

RAW_DATA = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA = PROJECT_ROOT / "data" / "processed"
MODELS = PROJECT_ROOT / "models"

RAW_DATA.mkdir(
    parents=True,
    exist_ok=True
)

PROCESSED_DATA.mkdir(
    parents=True,
    exist_ok=True
)

MODELS.mkdir(
    parents=True,
    exist_ok=True
)

RANDOM_STATE = 42

print("Project root:", PROJECT_ROOT)
print("Raw data:", RAW_DATA)
print("Processed data:", PROCESSED_DATA)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Project root: /content/drive/MyDrive/kinship_library
Raw data: /content/drive/MyDrive/kinship_library/data/raw
Processed data: /content/drive/MyDrive/kinship_library/data/processed

## 2. Business understanding

### Reader need

Kinship Library is designed for readers who want to explore questions of ecological connection, meaning, embodied practice, Yoga philosophy, Ayurveda, Indian spirituality, and selected Indigenous knowledge traditions from South America.

Later, a reader may describe an experience such as fear of the future, ecological concern, disconnection from nature, or a search for meaning.

The recommender will not diagnose that person. It will retrieve books whose themes are semantically related to the reader's self described interest.

### Questions for this phase

1. Can we collect enough relevant books with meaningful descriptions and subjects?
2. Which sources provide the most complete metadata?
3. Which themes are overrepresented or underrepresented?
4. How much missing information do we have?
5. Are there extreme values or suspicious records that need inspection?

## 3. Search vocabulary

These queries are collection tools, not labels about what a book can psychologically help with.

In [13]:
THEME_QUERIES = {

    "humans_and_nature": [
        "ecology human nature",
        "environmental humanities",
        "more than human",
        "ecofeminism",
        "deep ecology",
        "human nature connection"
    ],

    "yoga_philosophy": [
        "Yoga Sutras Patanjali",
        "Vedas",
        "Upanishads",
        "Bhagavad Gita",
        "yoga philosophy"
    ],

    "yoga_way_of_life": [
        "eight limbs yoga",
        "pranayama yoga",
        "meditation yoga",
        "yoga way of life"
    ],

    "ayurveda_indian_spirituality": [
        "Ayurveda",
        "Vedanta",
        "Indian spirituality",
        "Autobiography of a Yogi",
        "Indian Tantra"
    ],

    "indigenous_knowledge_americas": [

        # Broad Indigenous knowledge
        "Traditional Ecological Knowledge",
        "Indigenous Knowledge ecology",
        "Indigenous ecological knowledge",
        "Indigenous land based knowledge",
        "Indigenous environmental knowledge",
        "biocultural knowledge Indigenous",

        # Cosmology and spirituality
        "Indigenous cosmology Americas",
        "Indigenous worldviews nature",
        "Indigenous spirituality nature",
        "Indigenous peoples human nature relationship",

        # South America
        "South American Indigenous knowledge",
        "South American Indigenous cosmology",
        "Andean Indigenous knowledge",
        "Andean cosmology",
        "Amazonian Indigenous knowledge",
        "Amazonian cosmology",
        "Amerindian cosmology",
        "Amerindian perspectivism",

        # Colombia
        "Indigenous knowledge Colombia",
        "Indigenous cosmology Colombia",
        "Kogi Colombia",
        "Kogi worldview",
        "Kogi cosmology",
        "Muisca Colombia",
        "Muisca worldview",
        "Muisca cosmology",
        "Kamentsa Colombia",
        "Embera Colombia",
        "Nasa Colombia",
        "Wayuu Colombia",

        # Other traditions of the Americas
        "Quechua Indigenous knowledge",
        "Aymara Indigenous knowledge",
        "Mapuche Indigenous knowledge",
        "Maya Indigenous cosmology",
        "Native American ecological knowledge"
    ]
}


SEED_TITLES = [
    "Staying with the Trouble",
    "Ancestral Future",
    "The Yoga Sutras of Patanjali",
    "Autobiography of a Yogi",
    "Bhagavad Gita",
]

## 4. Open Library collection

### Purpose

Use the Open Library Search API to collect multiple books per request.

### Important

The code caches the result as CSV so we do not call the API again every time we rerun the notebook.

In [14]:
OPEN_LIBRARY_FILE = RAW_DATA / "open_library_books.csv"

if OPEN_LIBRARY_FILE.exists():
    open_library_books = pd.read_csv(OPEN_LIBRARY_FILE)
    print("Loaded cached Open Library data:", len(open_library_books))

else:
    rows = []

    headers = {
        "User-Agent": "KinshipLibraryStudentProject"
    }

    for collection_theme, queries in THEME_QUERIES.items():

        print("\nCollecting theme:", collection_theme)

        for query in queries:

            print("Query:", query)

            params = {
                "q": query,
                "limit": 30,
                "fields": (
                    "key,title,author_name,first_publish_year,"
                    "subject,isbn,language,ratings_average,ratings_count"
                )
            }

            try:
                response = requests.get(
                    "https://openlibrary.org/search.json",
                    params=params,
                    headers=headers,
                    timeout=60
                )

                if response.status_code != 200:
                    print(
                        "Skipped:",
                        query,
                        "Status:",
                        response.status_code
                    )
                    continue

                data = response.json()

                for book in data.get("docs", []):

                    rows.append({
                        "source_id": book.get("key"),
                        "title": book.get("title"),
                        "author": ", ".join(
                            book.get("author_name", [])
                        ),
                        "description": np.nan,
                        "subjects": ", ".join(
                            book.get("subject", [])[:15]
                        ),
                        "published_year": book.get(
                            "first_publish_year"
                        ),
                        "average_rating": book.get(
                            "ratings_average"
                        ),
                        "ratings_count": book.get(
                            "ratings_count"
                        ),
                        "isbn": (
                            book.get("isbn", [np.nan])[0]
                            if book.get("isbn")
                            else np.nan
                        ),
                        "language": (
                            book.get("language", [np.nan])[0]
                            if book.get("language")
                            else np.nan
                        ),
                        "source": "open_library",
                        "collection_theme": collection_theme,
                        "search_query": query
                    })

                print(
                    "Collected:",
                    len(data.get("docs", [])),
                    "books"
                )

                # Give Open Library some time
                time.sleep(2)

            except requests.exceptions.Timeout:

                print(
                    "Timeout for:",
                    query,
                    "Skipping this query and continuing."
                )

                time.sleep(5)
                continue

            except requests.exceptions.RequestException as error:

                print(
                    "Request error for:",
                    query
                )

                print(error)

                time.sleep(5)
                continue

    open_library_books = pd.DataFrame(rows)

    open_library_books.to_csv(
        OPEN_LIBRARY_FILE,
        index=False
    )

    print("\nCollection finished")
    print("Total books collected:", len(open_library_books))
    print("Saved to:", OPEN_LIBRARY_FILE)

open_library_books.head()

Collecting theme: humans_and_nature
Query: ecology human nature
Collected: 30 books
Query: environmental humanities
Collected: 30 books
Query: more than human
Collected: 30 books
Query: ecofeminism
Collected: 30 books
Query: deep ecology
Collected: 30 books
Query: human nature connection
Collected: 30 books

Collecting theme: yoga_philosophy
Query: Yoga Sutras Patanjali
Collected: 30 books
Query: Vedas
Collected: 30 books
Query: Upanishads
Collected: 30 books
Query: Bhagavad Gita
Collected: 30 books
Query: yoga philosophy
Collected: 30 books

Collecting theme: yoga_way_of_life
Query: eight limbs yoga
Collected: 21 books
Query: pranayama yoga
Collected: 30 books
Query: meditation yoga
Collected: 30 books
Query: yoga way of life
Collected: 30 books

Collecting theme: ayurveda_indian_spirituality
Query: Ayurveda
Collected: 30 books
Query: Vedanta
Collected: 30 books
Query: Indian spirituality
Collected: 30 books
Query: Autobiography of a Yogi
Collected: 30 books
Query: Indian Tantra
Collected: 30 books

Collecting theme: indigenous_knowledge_americas
Query: Traditional Ecological Knowledge
Collected: 30 books
Query: Indigenous Knowledge ecology
Collected: 30 books
Query: Indigenous ecological knowledge
Collected: 30 books
Query: Indigenous land based knowledge
Collected: 14 books
Query: Indigenous environmental knowledge
Collected: 30 books
Query: biocultural knowledge Indigenous
Collected: 18 books
Query: Indigenous cosmology Americas
Collected: 22 books
Query: Indigenous worldviews nature
Collected: 14 books
Query: Indigenous spirituality nature
Collected: 30 books
Query: Indigenous peoples human nature relationship
Collected: 21 books
Query: South American Indigenous knowledge
Collected: 23 books
Query: South American Indigenous cosmology
Collected: 1 books
Query: Andean Indigenous knowledge
Collected: 14 books
Query: Andean cosmology
Collected: 20 books
Query: Amazonian Indigenous knowledge
Collected: 0 books
Query: Amazonian cosmology
Collected: 2 books
Query: Amerindian cosmology
Collected: 8 books
Query: Amerindian perspectivism
Collected: 0 books
Query: Indigenous knowledge Colombia
Collected: 5 books
Query: Indigenous cosmology Colombia
Collected: 1 books
Query: Kogi Colombia
Collected: 12 books
Query: Kogi worldview
Collected: 0 books
Query: Kogi cosmology
Collected: 1 books
Query: Muisca Colombia
Collected: 30 books
Query: Muisca worldview
Collected: 0 books
Query: Muisca cosmology
Collected: 1 books
Query: Kamentsa Colombia
Collected: 3 books
Query: Embera Colombia
Collected: 30 books
Query: Nasa Colombia
Collected: 30 books
Query: Wayuu Colombia
Collected: 30 books
Query: Quechua Indigenous knowledge
Collected: 3 books
Query: Aymara Indigenous knowledge
Collected: 2 books
Query: Mapuche Indigenous knowledge
Collected: 4 books
Query: Maya Indigenous cosmology
Collected: 4 books
Query: Native American ecological knowledge
Collected: 21 books

Collection finished
Total books collected: 1075
Saved to: /content/drive/MyDrive/kinship_library/data/raw/open_library_books.csv

,source_id,title,author,description,subjects,published_year,average_rating,ratings_count,isbn,language,source,collection_theme,search_query
0,/works/OL6772557W,The ecology of human development,Urie Bronfenbrenner,NaN,"Child psychology, Research, Human Development,...",1979.0,5.000000,1.0,9780674224575,eng,open_library,humans_and_nature,ecology human nature
1,/works/OL3458484W,People and nature,Emilio F. Moran,NaN,"Effect of environment on, Effect of environmen...",2006.0,NaN,NaN,1118877411,eng,open_library,humans_and_nature,ecology human nature
2,/works/OL2990533W,The green imperative,"Victor J. Papanek, Victor Papanek",NaN,"Design, industrial, Environmental aspects, Env...",1995.0,NaN,NaN,9780500296196,eng,open_library,humans_and_nature,ecology human nature
3,/works/OL1805267W,Design with nature,Ian L. McHarg,NaN,"Effect of environment on, Effect of human bein...",1969.0,4.333334,6.0,047111460X,eng,open_library,humans_and_nature,ecology human nature
4,/works/OL2911248W,"The death of nature: women, ecology, and the s...",Carolyn Merchant,NaN,"Human ecology, Philosophy of nature, Social as...",1980.0,NaN,NaN,9780062505712,eng,open_library,humans_and_nature,ecology human nature

In [15]:
print("Books collected:", len(open_library_books))
print("Saved at:", OPEN_LIBRARY_FILE)
print("File exists:", OPEN_LIBRARY_FILE.exists())

Books collected: 1075
Saved at: /content/drive/MyDrive/kinship_library/data/raw/open_library_books.csv
File exists: True

In [16]:
print(OPEN_LIBRARY_FILE)

print(
    "File exists:",
    OPEN_LIBRARY_FILE.exists()
)

/content/drive/MyDrive/kinship_library/data/raw/open_library_books.csv
File exists: True

## 5. Books to Scrape sample

### Purpose

Demonstrate web scraping with a site built for scraping practice.

This sample is kept separate from the thematic model because it does not provide the rich descriptions we need for semantic recommendation.

In [ ]:
SCRAPED_FILE = RAW_DATA / "books_to_scrape.csv"

if SCRAPED_FILE.exists():
    scraped_books = pd.read_csv(SCRAPED_FILE)
    print("Loaded cached scraped data:", len(scraped_books))

else:
    rating_map = {
        "One": 1,
        "Two": 2,
        "Three": 3,
        "Four": 4,
        "Five": 5
    }

    rows = []

    for page in range(1, 6):
        url = f"https://books.toscrape.com/catalogue/page-{page}.html"
        response = requests.get(url, timeout=30)

        if response.status_code != 200:
            print("Skipped page:", page)
            continue

        soup = BeautifulSoup(response.text, "html.parser")

        for book in soup.select("article.product_pod"):
            rating_word = book.p.get("class", ["", ""])[1]

            rows.append({
                "title": book.h3.a["title"],
                "price": book.select_one(".price_color").get_text(strip=True),
                "rating": rating_map.get(rating_word),
                "availability": book.select_one(".availability").get_text(strip=True),
                "source": "books_to_scrape"
            })

        time.sleep(1)

    scraped_books = pd.DataFrame(rows)
    scraped_books.to_csv(SCRAPED_FILE, index=False)

scraped_books.head()

,title,price,rating,availability,source
0,A Light in the Attic,Â£51.77,3,In stock,books_to_scrape
1,Tipping the Velvet,Â£53.74,1,In stock,books_to_scrape
2,Soumission,Â£50.10,1,In stock,books_to_scrape
3,Sharp Objects,Â£47.82,4,In stock,books_to_scrape
4,Sapiens: A Brief History of Humankind,Â£54.23,5,In stock,books_to_scrape

## 7. Clean the thematic catalogue

### Purpose

Standardize types, remove obvious duplicates, inspect missing values, and create simple quality features.

In [17]:
books = open_library_books.copy()

books["title"] = books["title"].astype("string").str.strip()
books["author"] = books["author"].astype("string").str.strip()
books["subjects"] = books["subjects"].astype("string").str.strip()

books["published_year"] = pd.to_numeric(
    books["published_year"],
    errors="coerce"
)

books["average_rating"] = pd.to_numeric(
    books["average_rating"],
    errors="coerce"
)

books["ratings_count"] = pd.to_numeric(
    books["ratings_count"],
    errors="coerce"
)

books = books.dropna(subset=["title"])

books = books.drop_duplicates(
    subset=["title", "author"],
    keep="first"
)

books = books.reset_index(drop=True)

books["subject_count"] = (
    books["subjects"]
    .fillna("")
    .apply(lambda text: 0 if text == "" else len(text.split(",")))
)

books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 925 entries, 0 to 924
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   source_id         925 non-null    object
 1   title             925 non-null    string
 2   author            925 non-null    string
 3   description       0 non-null      float64
 4   subjects          925 non-null    string
 5   published_year    917 non-null    float64
 6   average_rating    113 non-null    float64
 7   ratings_count     113 non-null    float64
 8   isbn              802 non-null    object
 9   language          878 non-null    object
 10  source            925 non-null    object
 11  collection_theme  925 non-null    object
 12  search_query      925 non-null    object
 13  subject_count     925 non-null    int64
dtypes: float64(4), int64(1), object(6), string(3)
memory usage: 101.3+ KB

In [18]:
CLEAN_FILE = PROCESSED_DATA / "books_clean.csv"

books.to_csv(
    CLEAN_FILE,
    index=False
)

print("Saved:", CLEAN_FILE)
print("Rows:", len(books))
print("File exists:", CLEAN_FILE.exists())

Saved: /content/drive/MyDrive/kinship_library/data/processed/books_clean.csv
Rows: 925
File exists: True

## 7.1 Looking for descriptions

In [19]:
import requests
import time


def get_open_library_description(source_id):

    if pd.isna(source_id):
        return np.nan

    work_id = str(source_id).replace("/works/", "")

    url = (
        "https://openlibrary.org/works/"
        + work_id
        + ".json"
    )

    try:

        response = requests.get(
            url,
            timeout=30
        )

        if response.status_code != 200:
            return np.nan

        data = response.json()

        description = data.get(
            "description"
        )

        if isinstance(description, dict):
            description = description.get(
                "value"
            )

        if description:
            return description

        return np.nan

    except requests.exceptions.RequestException:
        return np.nan

## Missing values

In [20]:
missing_values = pd.DataFrame({
    "missing_count": books.isnull().sum(),
    "missing_percent": (books.isnull().mean() * 100).round(2)
}).sort_values("missing_percent", ascending=False)

missing_values

                  missing_count  missing_percent
description                 925           100.00
average_rating              812            87.78
ratings_count               812            87.78
isbn                        123            13.30
language                     47             5.08
published_year                8             0.86
subjects                      0             0.00
author                        0             0.00
source_id                     0             0.00
title                         0             0.00
source                        0             0.00
collection_theme              0             0.00
search_query                  0             0.00
subject_count                 0             0.00

In [21]:
print("Total collected records:", len(open_library_books))

print(
    "Unique Open Library IDs:",
    open_library_books["source_id"].nunique()
)

duplicate_ids = (
    open_library_books["source_id"]
    .duplicated(keep=False)
    .sum()
)

print(
    "Records belonging to duplicated book IDs:",
    duplicate_ids
)

Total collected records: 1075
Unique Open Library IDs: 962
Records belonging to duplicated book IDs: 184

In [22]:
print("Total books:", len(open_library_books))

display(
    open_library_books[
        "collection_theme"
    ].value_counts()
)

display(
    open_library_books[
        [
            "title",
            "author",
            "collection_theme",
            "search_query"
        ]
    ].sample(
        min(20, len(open_library_books)),
        random_state=42
    )
)

Total books: 1075

collection_theme
indigenous_knowledge_americas    484
humans_and_nature                180
yoga_philosophy                  150
ayurveda_indian_spirituality     150
yoga_way_of_life                 111
Name: count, dtype: int64

,title,author,collection_theme,search_query
428,The Way of Aikido,George Burr Leonard,yoga_way_of_life,yoga way of life
312,I-God,Gnanavallal Paranjothi Mahan,yoga_philosophy,yoga philosophy
306,Tree of Yoga,B. K. S. Iyengar,yoga_philosophy,yoga philosophy
141,Deep ecology,Michael Tobias,humans_and_nature,deep ecology
273,The Bhagavad-Gita,Edwin Arnold,yoga_philosophy,Bhagavad Gita
996,El pensamiento de la comunidad nasa yuwe,Alexander Ávila Martínez,indigenous_knowledge_americas,Nasa Colombia
825,The diversity of international law,Kalliopi Koufa,indigenous_knowledge_americas,Indigenous peoples human nature relationship
247,Twenty-Eight Upanishads (Îsha & Others).,Upanishads Upanishads,yoga_philosophy,Upanishads
583,The Niśvāsatattvasaṃhitā,"Dominic Goodall, Alexis Sanderson, H. Isaacson",ayurveda_indian_spirituality,Indian Tantra
51,Environmental science,"Eldon D. Enger, Richard J. Kormelink, Bradley ...",humans_and_nature,environmental humanities
661,"Traditional Ecological Knowledge , Ethnoecolog...","Tyler Pounds, New Mexico State University Writ...",indigenous_knowledge_americas,Indigenous ecological knowledge
328,Pātañjala Yoga philosophy,Koichi Yamashita,yoga_philosophy,yoga philosophy
361,Pranayama Yoga Asana,Anand Gupta,yoga_way_of_life,pranayama yoga
718,Sacred ecology,Fikret Berkes,indigenous_knowledge_americas,Indigenous environmental knowledge
158,Wittgenstein,P. M. S. Hacker,humans_and_nature,human nature connection
367,Breathing life,Coudoux Yogi.,yoga_way_of_life,pranayama yoga
318,Yoga Philosophy and Practice,Shyam Mehta,yoga_philosophy,yoga philosophy
88,Design for More-Than-Human Futures,"Martín Tironi, Marcos Chilet, Pablo Hermansen,...",humans_and_nature,more than human
652,African Indigenous Ecological Knowledge Systems,Ikechukwu Anthony Kanu,indigenous_knowledge_americas,Indigenous ecological knowledge
973,Las que cuidan el fogón,Magdalena Ramnek,indigenous_knowledge_americas,Embera Colombia

In [25]:
duplicate_books = (
    open_library_books[
        open_library_books["source_id"].duplicated(
            keep=False
        )
    ]
    .sort_values("source_id")
)

display(
    duplicate_books[
        [
            "source_id",
            "title",
            "author",
            "collection_theme",
            "search_query"
        ]
    ].head()
)

,source_id,title,author,collection_theme,search_query
627,/works/OL1054919W,Biopiracy,Vandana Shiva,indigenous_knowledge_americas,Indigenous Knowledge ecology
701,/works/OL1054919W,Biopiracy,Vandana Shiva,indigenous_knowledge_americas,Indigenous environmental knowledge
657,/works/OL1054919W,Biopiracy,Vandana Shiva,indigenous_knowledge_americas,Indigenous ecological knowledge
218,/works/OL11500W,The religion and philosophy of the Veda and Up...,Arthur Berriedale Keith,yoga_philosophy,Vedas
246,/works/OL11500W,The religion and philosophy of the Veda and Up...,Arthur Berriedale Keith,yoga_philosophy,Upanishads

In [26]:
indigenous_books = open_library_books[
    open_library_books["collection_theme"]
    == "indigenous_knowledge_americas"
]

display(
    indigenous_books[
        [
            "title",
            "author",
            "search_query",
            "subjects"
        ]
    ].sample(
        min(30, len(indigenous_books)),
        random_state=42
    )
)

,title,author,search_query,subjects
1009,Study of future world markets for agricultural...,F. W. Gobetz,Nasa Colombia,"Aeronautics in agriculture, Aerial fertilizing"
1065,The Water Walker,Joanne Robertson,Native American ecological knowledge,"JUVENILE NONFICTION, Savoirs écologiques tradi..."
772,Thai folklore,"Sirāphō̜n Thitathān Na Thalāng, Čhulālongkō̜nm...",Indigenous worldviews nature,"Social life and customs, Folklore, Tales, Mann..."
1037,Desecrated land,"Roberto Pineda Camacho, Organización Nacional ...",Wayuu Colombia,"Natural resources, Economic development projec..."
888,The occult life of things,Fernando Santos-Granero,Amazonian cosmology,"Material culture, Indians of South America, Ce..."
739,Biodiversity and the law,Charles R. McManis,biocultural knowledge Indigenous,"Intellectual property, Biotechnology, Law and ..."
971,Semejantes a los dioses,Luis Guillermo Vasco Uribe,Embera Colombia,"Chamí baskets, Chamí pottery, Keramik, Korbwar..."
977,El jaibaná en la encrucijada,Pablo Jaramillo Salazar,Embera Colombia,"Embera Indians, Rites and ceremonies, Religion..."
1070,Understanding child abuse and neglect,Cynthia Crosson-Tower,Native American ecological knowledge,"Social work with children, Services for, Child..."
818,The Oxford handbook on the United Nations,"Thomas George Weiss, Sam Daws",Indigenous peoples human nature relationship,"Handbooks, manuals, United Nations, Internatio..."
600,Traditional Ecological Knowledge,Robert Earle Johannes,Traditional Ecological Knowledge,"Ecology, Nature conservation, Traditional ecol..."
766,Indigenous Peoples Wisdom and Power,"Julian Kunnie, Nomalungelo L. Goduka",Indigenous worldviews nature,"Religion, Ethnoscience, Indigenous peoples, Et..."
1069,Our Ice Is Vanishing,Shelley Wright,Native American ecological knowledge,"Inuit, canada, Sea ice, Climatic changes, Cana..."
914,Introducción a las artes adivinatorias como pr...,,Kogi Colombia,"divination, Felipe Cárdenas, Kogis, Colombia, ..."
802,Contemporary Issues in African Sciences and Sc...,"Akwasi Asabere-Ameyaw, George J. Sefa Dei, Kol...",Indigenous spirituality nature,"Science, study and teaching, Science, africa, ..."
1018,La masacre de Bahía Portete,Comisión Nacional de Reparación y Reconciliaci...,Wayuu Colombia,"Goajiro Indians, Massacres, Race relations, Go..."
675,"Intellectual Property, Indigenous People and T...",Peter Drahos,Indigenous ecological knowledge,"Intellectual property, Indigenous peoples, leg..."
621,"Indigenous Knowledge, Ecology, and Evolutionar...",Raymond Pierotti,Indigenous Knowledge ecology,"Indigenous peoples, Evolution, Experiential le..."
829,A TOUR OF THE WORLD,"Malik Mansab Khan, Muhammad Rafique Abdul Aziz",Indigenous peoples human nature relationship,"Political Geography, Global Politics, Geopolit..."
681,Indigenous Land-Based Knowledge and Sustainabi...,"Ranjan Datta, Jebunnessa Chapola, John Bosco A...",Indigenous land based knowledge,Economic history
838,Psychiatrist and traditional healers,"Mario Incayawar, Ronald Wintrob, Lise Bouchard...",South American Indigenous knowledge,"Cross-Cultural Comparison, Traditional Medicin..."
1068,"Seed sovereignty, food security",Vandana Shiva,Native American ecological knowledge,"Plant genetic engineering, Agricultural biotec..."
872,Andean Aesthetics and Anticolonial Resistance,"Omar Rivera, Monika Kirloskar-Steinbach",Andean cosmology,"Aesthetics, Decolonization, Indian philosophy,..."
1054,Tending the Wild,"M. Kat Anderson, Kat Anderson",Native American ecological knowledge,"Indians of north america, agriculture, Indians..."
624,The world Wolf made,Raymond John Pierotti,Indigenous Knowledge ecology,"Traditional ecological knowledge, Evolution (B..."
744,INTERNATIONAL RELATIONS IN UNCOMMON PLACES: IN...,J. MARSHALL BEIER,Indigenous cosmology Americas,"Indians of north america, government relations..."
1066,Climate Change and Indigenous Peoples in the U...,"Julie Koppel Maldonado, Benedict Colombi, Raju...",Native American ecological knowledge,"Climatic changes, Indians of north america, so..."
1060,"Structure, knowledge and representation in the...","R. Tom Zuidema, Gary Urton",Native American ecological knowledge,"Incas, Addresses, essays, lectures"
668,Indigenous Intergenerational Resilience,Lewis Williams,Indigenous ecological knowledge,"Traditional ecological knowledge, Ethnoecology..."
661,"Traditional Ecological Knowledge , Ethnoecolog...","Tyler Pounds, New Mexico State University Writ...",Indigenous ecological knowledge,"Science, Social sciences"

## 8. Google Books Enrichment

Our first Colab test returned HTTP 429 even for one request.

But, I got an API Books, and created a project and now we can enrich the descriptions with google books



```
# Open Library clean catalogue
          ↓
       Has ISBN?
       ↙      ↘
     Yes       No
      ↓         ↓
ISBN search   Title + author search
      ↓         ↓
       Google Books
            ↓
Verify match
            ↓
Collect description
categories
publisher
Google Books ID
            ↓
Cache results
            ↓
Merge with books
```

In [27]:
import requests
import time
import numpy as np
import pandas as pd

In [28]:
from google.colab import userdata

GOOGLE_BOOKS_API_KEY = userdata.get(
    "API_key_books"
)

print("API key loaded successfully")

API key loaded successfully

## 8.2 Full Google Books enrichment cell

In [29]:
from google.colab import userdata
import requests
import time
import pandas as pd
import numpy as np

GOOGLE_BOOKS_API_KEY = userdata.get(
    "API_key_books"
)

GOOGLE_CACHE_FILE = (
    RAW_DATA / "google_books_enrichment.csv"
)

print("Cache location:")
print(GOOGLE_CACHE_FILE)

Cache location:
/content/drive/MyDrive/kinship_library/data/raw/google_books_enrichment.csv

In [30]:
def search_google_book(row):

    url = "https://www.googleapis.com/books/v1/volumes"

    isbn = row["isbn"]
    title = row["title"]
    author = row["author"]

    # Prefer ISBN because it gives us a stronger match
    if pd.notna(isbn):
        query = f"isbn:{isbn}"

    else:
        query = f'intitle:"{title}"'

        if pd.notna(author):
            query += f' inauthor:"{author}"'

    params = {
        "q": query,
        "maxResults": 1,
        "printType": "books",
        "key": GOOGLE_BOOKS_API_KEY
    }

    try:

        response = requests.get(
            url,
            params=params,
            timeout=30
        )

        # Successful request
        if response.status_code == 200:

            data = response.json()

            # Google searched successfully
            # but did not find the book
            if data.get("totalItems", 0) == 0:

                return {
                    "status": "not_found"
                }

            item = data["items"][0]

            info = item.get(
                "volumeInfo",
                {}
            )

            return {
                "status": "found",
                "google_books_id": item.get("id"),
                "google_title": info.get("title"),
                "google_authors": ", ".join(
                    info.get("authors", [])
                ),
                "description": info.get("description"),
                "categories": ", ".join(
                    info.get("categories", [])
                ),
                "publisher": info.get("publisher"),
                "google_published_date": info.get(
                    "publishedDate"
                ),
                "google_average_rating": info.get(
                    "averageRating"
                ),
                "google_ratings_count": info.get(
                    "ratingsCount"
                )
            }

        # Rate limit
        elif response.status_code == 429:

            return {
                "status": "rate_limited"
            }

        # Other HTTP problem
        else:

            return {
                "status": (
                    "http_"
                    + str(response.status_code)
                )
            }

    except requests.exceptions.RequestException:

        return {
            "status": "request_error"
        }

In [31]:
# Load previous progress if available

if GOOGLE_CACHE_FILE.exists():

    google_cache = pd.read_csv(
        GOOGLE_CACHE_FILE
    )

    print(
        "Previous results loaded:",
        len(google_cache)
    )

else:

    google_cache = pd.DataFrame()

    print(
        "No previous cache found."
    )


# IDs already properly processed

if len(google_cache) > 0:

    completed_ids = set(
        google_cache.loc[
            google_cache["status"].isin(
                ["found", "not_found"]
            ),
            "source_id"
        ]
        .astype(str)
    )

else:

    completed_ids = set()


print(
    "Already completed:",
    len(completed_ids)
)

print(
    "Books remaining:",
    len(books) - len(completed_ids)
)

No previous cache found.
Already completed: 0
Books remaining: 925

In [32]:
new_results = []

rate_limit_reached = False


for index, row in books.iterrows():

    source_id = str(
        row["source_id"]
    )

    # Do not request books already processed
    if source_id in completed_ids:
        continue


    result = search_google_book(row)

    status = result["status"]


    # STOP if Google rate limits us
    if status == "rate_limited":

        print()
        print("Google Books rate limit reached.")
        print("Collection stopped safely.")
        print("Last attempted book:")
        print(row["title"])

        rate_limit_reached = True

        break


    # Store identifying information
    result["source_id"] = source_id
    result["open_library_title"] = row["title"]
    result["open_library_author"] = row["author"]
    result["isbn"] = row["isbn"]

    new_results.append(
        result
    )


    print(
        len(completed_ids)
        + len(new_results),
        "/",
        len(books),
        row["title"],
        "|",
        status
    )


    # Save every 10 books
    if len(new_results) >= 10:

        batch = pd.DataFrame(
            new_results
        )

        google_cache = pd.concat(
            [
                google_cache,
                batch
            ],
            ignore_index=True
        )

        google_cache.to_csv(
            GOOGLE_CACHE_FILE,
            index=False
        )

        completed_ids.update(
            batch["source_id"]
            .astype(str)
        )

        new_results = []

        print(
            "Progress saved to Drive:",
            len(google_cache)
        )


    # Slower than yesterday
    time.sleep(5)

1 / 925 The ecology of human development | found
2 / 925 People and nature | http_503
3 / 925 The green imperative | found
4 / 925 Design with nature | found
5 / 925 The death of nature: women, ecology, and the scientific revolution | found
6 / 925 Human geography | found
7 / 925 Galen's Prophecy | found
8 / 925 Man's responsibility for nature | found
9 / 925 Ecological Transition | found
10 / 925 Biomimicry | found
Progress saved to Drive: 10
11 / 925 Sex, ecology, spirituality | found
12 / 925 Team human | found
13 / 925 Ecology and equity | found
14 / 925 Human Ecology | found
15 / 925 Understanding Human Ecology | not_found
16 / 925 Ecological revolutions | not_found
17 / 925 Human ecology | found
18 / 925 Ecology | found
19 / 925 Man, nature, and ecology | found
20 / 925 Human ecology | found
Progress saved to Drive: 20
21 / 925 Environmental philosophy | found
22 / 925 Sacred ecology | not_found
23 / 925 Human dimensions of ecological restoration | found
24 / 925 The forest and the sea | not_found
25 / 925 Man's nature and nature's man | found
26 / 925 Being Ecological | not_found
27 / 925 Human-nature interactions in the anthropocene | found
28 / 925 Last Child in the Woods | not_found
29 / 925 Islands of Abandonment | not_found
30 / 925 Natural capital and human economic survival | not_found
Progress saved to Drive: 30
31 / 925 Environmental Humanities and Theologies | found
32 / 925 Routledge Handbook of the Digital Environmental Humanities | found
33 / 925 Environmental science | found
34 / 925 Environmental Human Rights | found
35 / 925 Environmental Human Rights | found
36 / 925 The Environmental Humanities | not_found
37 / 925 Introduction to the Environmental Humanities | found
38 / 925 Global Ecologies and the Environmental Humanities | found
39 / 925 Disability Studies and the Environmental Humanities | not_found
40 / 925 Environmental Science | found
Progress saved to Drive: 40
41 / 925 Routledge Companion to the Environmental Humanities | not_found
42 / 925 Environmental Humanities and the Uncanny | found
43 / 925 Environmental Humanities | not_found
44 / 925 Epistemic Justice, Mindfulness, and the Environmental Humanities | not_found
45 / 925 Environmental Human Rights and Climate Change | not_found
46 / 925 Avatar and Nature Spirituality

                Environmental Humanities | found
47 / 925 Religion, Narrative, and the Environmental Humanities | found
48 / 925 Environmental Humanities in the New Himalayas | found
49 / 925 Cambridge Companion to Environmental Humanities | found
50 / 925 Environmental Humanities of Extraction in Africa | found
Progress saved to Drive: 50
51 / 925 Grounding Education in Environmental Humanities | not_found
52 / 925 Environmental science | found
53 / 925 Environmental science | found
54 / 925 Eighteenth-Century Environmental Humanities | found
55 / 925 Ecological Exile | not_found
56 / 925 Environmental science | found
57 / 925 Bloomsbury Handbook to the Medical-Environmental Humanities | found
58 / 925 An Approach to environmental psychology | found
59 / 925 Rethinking Invasion Ecologies from the Environmental Humanities | found
60 / 925 Environmental Human Rights in the Anthropocene | found
Progress saved to Drive: 60
61 / 925 More Than Human | found
62 / 925 The spell of the sensuous | found
63 / 925 No more than human | found
64 / 925 More Than Human | found
65 / 925 Participatory Research in More-Than-Human Worlds | found
66 / 925 More than human | found
67 / 925 More Than Human | not_found
68 / 925 Injecting Bodies in More-Than-human Worlds | found
69 / 925 Data Selves | not_found
70 / 925 Walking Methodologies in a More-Than-human World | not_found
Progress saved to Drive: 70
71 / 925 Matters of Care | not_found
72 / 925 Healthy Urban Environments | not_found
73 / 925 Humans, Animals and Biopolitics | not_found
74 / 925 Radical Environmentalism | found
75 / 925 Designing More-Than-Human Smart Cities | found
76 / 925 I Love My Dog More Than Humans | found
77 / 925 More Than Human | found
78 / 925 More-Than-Human Aging | not_found
79 / 925 Anthropocene Psychology | not_found
80 / 925 Biopolitics of the More-Than-Human | found
Progress saved to Drive: 80
81 / 925 More-than-Human Sociology | not_found
82 / 925 More-Than-Human Aesthetics | found
83 / 925 More-Than-Human Choreography | found
84 / 925 The Spell of the Sensuous | not_found
85 / 925 City Is More Than Human | found
86 / 925 Digital Ecologies | found
87 / 925 More-Than-Human Design in Practice | found
88 / 925 Design for More-Than-Human Futures | found
89 / 925 Mammoth Books Presents More Than Human | found
90 / 925 Ecofeminism | found
Progress saved to Drive: 90
91 / 925 Ecofeminism | found
92 / 925 Ecofeminism | found
93 / 925 Healing the Wounds | found
94 / 925 Ecofeminism and Systems Thinking | not_found
95 / 925 Reweaving The World | found
96 / 925 Ecofeminism | found
97 / 925 Ecofeminism And The Sacred | found
98 / 925 Ecofeminism as politics | not_found
99 / 925 What is ecofeminism? | found
100 / 925 Ecofeminism | not_found
Progress saved to Drive: 100
101 / 925 Ecofeminism revisited | found
102 / 925 Ecofeminism and globalization | found
103 / 925 Critical Ecofeminism | found
104 / 925 Contemporary Perspectives on Ecofeminism | found
105 / 925 Literature and Ecofeminism | not_found
106 / 925 Ecofeminism | found
107 / 925 Longing for running water | found
108 / 925 Ecofeminism and the Indian Novel | not_found
109 / 925 D. H. Lawrence, Ecofeminism and Nature | found
110 / 925 Changing Nature of Eco/Feminism | not_found
Progress saved to Drive: 110
111 / 925 Place and Postcolonial Ecofeminism | found
112 / 925 Ecofeminism on the Edge | found
113 / 925 Routledge Handbook of Ecofeminism and Literature | not_found
114 / 925 Ecofeminism reader | not_found
115 / 925 Ecofeminism in Dialogue | found
116 / 925 Ecofeminism | found
117 / 925 What is ecofeminism anyway? | not_found
118 / 925 Queer Ecofeminism | not_found
119 / 925 Deep Ecology & Anarchism | found
120 / 925 Deep ecology | found
Progress saved to Drive: 120
121 / 925 THE DEEP ECOLOGICAL MOVEMENT: SOME PHILOSOPHICAL ASPECTS | not_found
122 / 925 Deep Ecology for the 21st century | found
123 / 925 Deep Ecology Movement | found
124 / 925 Eco-socialism | found
125 / 925 DEEP ECOLOGY | not_found
126 / 925 Deep Ecology | found
127 / 925 Spinoza and Deep Ecology | found
128 / 925 Gaia Psyche and Deep Ecology | found
129 / 925 Buddhism and Deep Ecology | not_found
130 / 925 How deep is deep ecology? | found
Progress saved to Drive: 130
131 / 925 Deep Ecology | found
132 / 925 Buddhism and Deep Ecology | not_found
133 / 925 Deep Ecology, Business Ethics and Personal Responsibility | found
134 / 925 Toward a naturalistic political theory | found
135 / 925 Dark night, early dawn | found
136 / 925 Spinoza and the deep ecology movement | found
137 / 925 Deep ecology | found
138 / 925 Discussion course on exploring deep ecology | found
139 / 925 Deep Ecology | not_found
140 / 925 Deep ecology | found
Progress saved to Drive: 140
141 / 925 Beneath the surface | found
142 / 925 Approaching deep ecology | found
143 / 925 Regarding nature | not_found
144 / 925 Living Deep Ecology | found
145 / 925 The Culture of Extinction | found
146 / 925 POSTMODERN ENVIRONMENTALISM: A CRITIQUE OF DEEP ECOLOGY | not_found
147 / 925 Gandhi and deep ecology | found
148 / 925 A critique of deep ecology | found
149 / 925 Building for Life | found
150 / 925 Loneliness | found
Progress saved to Drive: 150
151 / 925 Social Intelligence | found
152 / 925 The good in nature and humanity | found
153 / 925 Place-based education | found
154 / 925 Connected Lives | found
155 / 925 Nature and culture | not_found
156 / 925 Wittgenstein | found
157 / 925 Survival of the Sickest | not_found
158 / 925 Natural learning for a connected world | found
159 / 925 Human transit | found
160 / 925 Urbanizing Nature | found
Progress saved to Drive: 160
161 / 925 Consciousness Connection | not_found
162 / 925 The good in nature and humanity : connecting science, religion, and spirituality with the natural world | found
163 / 925 Get Outside! | http_503
164 / 925 Lexicon medicum | found
165 / 925 Literature. The Human Experience, Reading and Writing--Twelfth Edition | found
166 / 925 Humanity's Connection to the Natural World | not_found
167 / 925 Planning connections | found
168 / 925 The primordial bond | found
169 / 925 Awakening to Nature | found
170 / 925 The primordial bond | found
Progress saved to Drive: 170
171 / 925 Earth signs | found
172 / 925 The voice of the infinite in the small | not_found
173 / 925 Connection to Nature, Deep Ecology, and Conservation Social Science | found
174 / 925 Human Natural Form : a Close Connection with Intellect | not_found
175 / 925 Connect Access Card for Personality Psychology | not_found
176 / 925 Earth changes and the human-cosmic connection | found
177 / 925 Patanjali yoga sutras | found
178 / 925 Yogasūtra | found
179 / 925 Yoga sutras | not_found
180 / 925 Light on the Yoga Sutras of Patanjali | found
Progress saved to Drive: 180
181 / 925 Patanjali Yoga Sutras | found
182 / 925 Yoga-Sutra | found
183 / 925 The Yoga Sutras of Patanjali | found
184 / 925 Yoga | found
185 / 925 The yoga sutras of Patanjali | found
186 / 925 How to know God | not_found
187 / 925 Yoga-sutras | found
188 / 925 The Yoga-Sútra of Patañjali | found
189 / 925 Tree of Yoga | found
190 / 925 Yoga Sutras of Patanjali | found
Progress saved to Drive: 190
191 / 925 Yoga Sastra | found
192 / 925 Yoga Sutras of Patanjali | found
193 / 925 Yoga, the art of integration | not_found
194 / 925 Patanjali's Yoga Sutras | found
195 / 925 The Yoga Sutras of Patanjali | found
196 / 925 The Yoga sutras of Patañjali | not_found
197 / 925 Yoga Sutras of Patanjali | found
198 / 925 The Yoga Sutras Of Patanjali | found
199 / 925 Patanjali Yoga Sutras | found
200 / 925 The Yoga sutras of Patanjali | not_found
Progress saved to Drive: 200
201 / 925 Yoga sutras of Patanjali | found
202 / 925 Yogasūtra. English | found
203 / 925 Beyond The Siddhis | found
204 / 925 Patanjali's Yoga Sutras | found
205 / 925 Yoga Sutras of Patanjali | not_found
206 / 925 The Holy Vedas ; Rig Veda, Yajur Veda, Sama Veda, Atharva Veda | not_found
207 / 925 Rig-Veda | found
208 / 925 The Vedas | found
209 / 925 Atharva vēda | found
210 / 925 Der Rig-Veda, Part IV, Index | found
Progress saved to Drive: 210
211 / 925 Hymns to the mystic fire | not_found
212 / 925 Rig-Veda Sanhita | found
213 / 925 Rig-veda | not_found
214 / 925 The religion and philosophy of the Veda and Upanishads | found
215 / 925 Vedas | found
216 / 925 Building architecture of Sthāpatya Veda | found
217 / 925 Vedic hymns | not_found
218 / 925 The religion of the Veda = | found
219 / 925 The Vēdas | not_found
220 / 925 Nasty Nature (Horrible Science) | found
Progress saved to Drive: 220
221 / 925 The Holy Vedas | not_found
222 / 925 The Rig Veda | found
223 / 925 Human Physiology | found
224 / 925 The Atharvaveda | not_found
225 / 925 The Rig Veda | found
226 / 925 Atharva-Veda-Saṁhitā | found
227 / 925 The Vedas and Upanishads for Children | found
228 / 925 Sanskrit Grammar | found
229 / 925 Rig Veda | found
230 / 925 Sciences in the Vedas | found
Progress saved to Drive: 230
231 / 925 The Vedas | not_found
232 / 925 Rig Veda | found
233 / 925 The Holy Vedas | found
234 / 925 Rig-veda, oder, Die heiligen lieder der Brahmanen | found
235 / 925 Sam-Veda Sanhita | found
236 / 925 The Upanishads | found
237 / 925 Upanishads | found
238 / 925 The Upanishads. Tr. by F.M. Müller | found
239 / 925 Eight Upanishads | found
240 / 925 Ghar Ghar Upanishad | not_found
Progress saved to Drive: 240
241 / 925 The Upanishads | found
242 / 925 Twenty-Eight Upanishads (Îsha & Others). | found
243 / 925 Philosophie der Upanishad's | not_found
244 / 925 Ishavasya Upanishad | found
245 / 925 Mundaka Upanishad | found
246 / 925 The Upanishads | found
247 / 925 Niralamba Upanishad | found
248 / 925 Niralamba Upanishad (Vol 1) | found
249 / 925 The Upanishads | found
250 / 925 The Upanishads | found
Progress saved to Drive: 250
251 / 925 Mandukya Upanishad | found
252 / 925 The Upanishads | found
253 / 925 Upanishads | found
254 / 925 The Upanishads | not_found
255 / 925 The Upanishads | found
256 / 925 Upaniṣads | found
257 / 925 Dialogue with death | found
258 / 925 The Upanishads | found
259 / 925 Upanishads | found
260 / 925 Upanishads | found
Progress saved to Drive: 260
261 / 925 The Upanishads | found
262 / 925 Upanishads | found
263 / 925 Bhagavad-Gita | not_found
264 / 925 The Bhagavad gita | found
265 / 925 Shrimad Bhagvat | found
266 / 925 The Bhagavad-Gita | found
267 / 925 Bhagavad Gita | http_503
268 / 925 Bhagavad-Gita As It Is | found
269 / 925 The Bhagavad Gita | found
270 / 925 भगवद्गीता | found
Progress saved to Drive: 270
271 / 925 Paths to god | found
272 / 925 Bhagavad Gita | found
273 / 925 Bhagavad Gītā | found
274 / 925 The Bhagavad Gita | not_found
275 / 925 Shrimad bhagvad gita | not_found
276 / 925 The Bhagavad Gita | not_found
277 / 925 Srīmad Bhagavad-gītā | not_found
278 / 925 Bhagavad Gita | found
279 / 925 Bhagavad Gītā | found
280 / 925 The Bhagavad-gita | found
Progress saved to Drive: 280
281 / 925 Illuminations from the Bhagavad-gĩtã | found
282 / 925 Bhagavad Gita (Harvard Oriental) | not_found
283 / 925 Bhagavad Gita | found
284 / 925 The Bhagavad-Gita | found
285 / 925 Bhagavad Gita | found
286 / 925 Introduction to Bhagavad-gita | found
287 / 925 Bhagavad-Gita | found
288 / 925 Songs of the soul | not_found
289 / 925 The Bhagavad Gita | not_found
290 / 925 Perennial psychology of the Bhagavad Gita | found
Progress saved to Drive: 290
291 / 925 A Treatise on the Yoga Philosophy | not_found
292 / 925 Yoga philosophy | not_found
293 / 925 The Inner Tradition of Yoga | found
294 / 925 Yoga philosophy | found
295 / 925 Pantajali's Yoga Philosophy | found
296 / 925 The Yoga Tradition | found
297 / 925 Sūtras, Stories and Yoga Philosophy | found
298 / 925 Introduction to Yoga Philosophy | found
299 / 925 The Eight Limbs of Yoga | found
300 / 925 I-God | found
Progress saved to Drive: 300
301 / 925 Higher Psychical Development (Yoga Philosophy) an Outline of the Secret Hindu Teachings | found
302 / 925 Yoga Philosophy | found
303 / 925 Introduction to the Yoga Philosophy | found
304 / 925 Yoga Philosophy and Practice | found
305 / 925 A Treatise on the Yoga Philosophy | found
306 / 925 A Treatise On The Yoga Philosophy / By N.c. Paul | found
307 / 925 Yoga Sastra : The Yoga Sutras of Patenjali Examined | found
308 / 925 Yoga philosophy in relation to other systems of Indian thought | found
309 / 925 Yoga Philosophy | found
310 / 925 Exploring Yoga Philosophy | found
Progress saved to Drive: 310
311 / 925 Die Yoga-Philosophie Nach Dem Râjmârtanda | found
312 / 925 Higher psychical development | not_found
313 / 925 Pātañjala Yoga philosophy | found
314 / 925 Yoga Philosophy | found
315 / 925 Whoa-Ga! Eight Limbed Yoga for Horse/Rider Harmony | found
316 / 925 Eight limbs of yoga | not_found
317 / 925 Eight Limbs of Yoga | found
318 / 925 The 8 limbs of yoga | found
319 / 925 Eight Limbs of Yoga | found
320 / 925 Eight Limbs of Yoga for Modern Times | found
Progress saved to Drive: 320
321 / 925 Path to Liberation : Understanding the Eight Limbs of Yoga | not_found
322 / 925 Fallen Star | found
323 / 925 Yoga Through Christ | found
324 / 925 Rethinking Alcohol Through the Eight Limbs of Yoga | found
325 / 925 Eight Limbs of Yoga : a Holistic Guide for Daily Living | not_found
326 / 925 Exploring the Eight Limbs of Yoga : a Guide to the Spiritual Practice of Yoga | not_found
327 / 925 Marine on the Mat | found
328 / 925 Eight Limbs of Yoga - the Structure and Pacing of Self-Directed Spiritual Practice (Arabic Translation) | found
329 / 925 Eight Limbs of Yoga - the Structure and Pacing of Self-Directed Spiritual Practice : (AYP Enlightenment Series) | found
330 / 925 The yoga mind | found
Progress saved to Drive: 330
331 / 925 Do your om thing | found
332 / 925 Harmony with the Movement of the Universe | found
333 / 925 Sacred Kink | found
334 / 925 Pranayama Yoga | found
335 / 925 Light on prāṇāyāma | found
336 / 925 Pranayama yoga | found
337 / 925 Pranayama yoga | http_503
338 / 925 Pranayama Yoga | found
339 / 925 Pranayama Yoga | found
340 / 925 Pranayama Yoga for Health and Happiness | not_found
Progress saved to Drive: 340
341 / 925 Authentic Pranayama Yoga | not_found
342 / 925 Asana Pranayama Mudra Bandha | found
343 / 925 Pranayama Yoga Asana | found
344 / 925 Die Atemkunst des Pranayama-Yoga | not_found
345 / 925 Prana, Pranayama, Prana Vidya | found
346 / 925 Art du Souffle | found
347 / 925 Pranayama Ayurvedic Breathing Exercises : Mental Benefits of Practicing Breath Control | not_found
348 / 925 Prânayâma | found
349 / 925 Breathing life | found
350 / 925 The art of relaxation | found
Progress saved to Drive: 350
351 / 925 Asana, pranayama, mudra, bandha | found
352 / 925 Pranayama | not_found
353 / 925 The secrets of Prana, Pranayama & Yoga-asanas | found
354 / 925 Kumbhaka paddhati of Raghuvira | found
355 / 925 The Yoga of Breath | found
356 / 925 5 S of Yoga | found
357 / 925 Prana and pranayama | found
358 / 925 The correction of breathing difficulties by yoga pranayama | not_found
359 / 925 Yoga Teachers Manual of Pranayama | not_found
360 / 925 Teaching yoga | found
Progress saved to Drive: 360
361 / 925 Science of pranayama | found
362 / 925 Pranayama Beyond the Fundamentals | found
363 / 925 The complete yoga book | found
364 / 925 Meditations | found
365 / 925 Meditation | not_found
366 / 925 Patanjali's Meditation Yoga | found
367 / 925 Tibetan yoga | not_found
368 / 925 Meditation Yoga | found
369 / 925 Journey of awakening | found
370 / 925 Breathe. Live. Be : Journal Blank Lined 6X9 Yoga Meditation | found
Progress saved to Drive: 370
371 / 925 Meditation Yoga Coloring Book | found
372 / 925 Meditation, Yoga and the Secret Mystic Powers of Consciousness | not_found
373 / 925 Adult Creative Coloring Mandalas | found
374 / 925 Mindful Pregnancy | not_found
375 / 925 Mindful Pregnancy | found
376 / 925 Yoga Nidra | found
377 / 925 Power of Meditative Yoga | found
378 / 925 Meditation Yoga Coloring Book for Kids | not_found
379 / 925 Meditation Yoga Coloring Book for Adults | found
380 / 925 Meditation Yoga Coloring Book for Children | found
Progress saved to Drive: 380
381 / 925 Meditation Yoga Coloring Book | found
382 / 925 New Dimensions of Meditation-Yoga | found
383 / 925 Meditation Yoga Coloring Book | found
384 / 925 Meditation Yoga for Spiritual Discipline | found
385 / 925 Kinder Bewegen - Tanz, Meditation, Yoga | found
386 / 925 Meditations on Yoga by Osho (Osho Meditations) | not_found
387 / 925 The mindful way through pregnancy | found
388 / 925 Science of Meditation, Yoga, and Prayer | not_found
389 / 925 Heavily Meditated Yoga Zen Lotus Flower | not_found
390 / 925 Meditation Yoga Coloring Book | found
Progress saved to Drive: 390
391 / 925 Meditation Buddhism Om Zen Meditating Yoga | not_found
392 / 925 The way of the superior man | found
393 / 925 Derekh ha-yogah | not_found
394 / 925 The unseen hand | found
395 / 925 Yoga for Sex | found
396 / 925 Yoga | found
397 / 925 The yoga of Jesus | found
398 / 925 The hidden teaching beyond yoga | found
399 / 925 A fifth yoga | not_found
400 / 925 Jnana-yoga | found
Progress saved to Drive: 400
401 / 925 Decolonizing Yoga : from Critical to Cosmic Consciousness | found
402 / 925 Yoga | found
403 / 925 101 ways to live well | found
404 / 925 Yoga | not_found
405 / 925 Integral Yoga | found
406 / 925 How to practice | found
407 / 925 Yoga As A Way Of Life | not_found
408 / 925 The complete yoga of emotional-sexual life | found
409 / 925 The Way of Aikido | found
410 / 925 Don't sweat the small stuff-- and it's all small stuff | found
Progress saved to Drive: 410
411 / 925 Yoga : a Way of Life | found
412 / 925 The struggle for perfection | not_found

/tmp/ipykernel_955/338118846.py:65: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  google_cache = pd.concat(

551 / 925 The Niśvāsatattvasaṃhitā | not_found
552 / 925 The world of Tantra | not_found
553 / 925 Geschichte der indischen litteratur | found
554 / 925 Buddhist Tantra | not_found
555 / 925 The Tantras and their impact on Indian life | found
556 / 925 An Ancient Indian system of rasayana | found
557 / 925 Sanskrit manuscripts from Tibet | found
558 / 925 Traditional Ecological Knowledge and Natural Resource Management | found
559 / 925 Traditional Ecological Knowledge | found
560 / 925 Traditional Ecological Knowledge in Georgia | not_found
Progress saved to Drive: 560
561 / 925 Traditional Ecological Knowledge | found
562 / 925 Traditional ecological knowledge | found
563 / 925 Traditional Ecological Knowledge and Global Pandemics | found
564 / 925 The Traditional Ecological Knowledge of the Solega | found
565 / 925 Traditional Ecological Knowledge , Ethnoecology, It's Use in Indigenous Communities and Native America | not_found
566 / 925 Traditional Ecological Knowledge | found
567 / 925 Traditional ecological knowledge | not_found
568 / 925 Human impacts on Amazonia | not_found
569 / 925 Traditional Ecological Knowledge of Resource Management in Asia | found
570 / 925 Traditional Ecological Knowledge in Georgia | found
Progress saved to Drive: 570
571 / 925 Traditional Ecological Knowledge | found
572 / 925 Traditional ecological knowledge of mountain people | found
573 / 925 Traditional Ecological Knowledge and Global Pandemics | found
574 / 925 Indigenous traditional ecological knowledge in agroforestry | found
575 / 925 Traditional ecological knowledge and modern environmental assessment | found
576 / 925 Indigenous Critical Reflections on Traditional Ecological Knowledge | found
577 / 925 Traditional ecological knowledge camp in Fort Yukon | not_found
578 / 925 The Navajo and the animal people | found
579 / 925 Traditional ecological knowledge of salmon along the Yukon River | found
580 / 925 Exploring the role of traditional ecological knowledge in climate change initiatives | found
Progress saved to Drive: 580
581 / 925 Exploring the role of traditional ecological knowledge in climate change initiative | found
582 / 925 Whitefish | found
583 / 925 Voices from the bay | found
584 / 925 Indigenous Knowledge, Ecology, and Evolutionary Biology | not_found
585 / 925 Braiding Sweetgrass | found
586 / 925 Indigenous knowledge, ecology, and evolutionary biology | found
587 / 925 The world Wolf made | not_found
588 / 925 Ancient Pathways Ancestral Knowledge Ethnobotany And Ecological Wisdom Of Indigenous Peoples Of Northwestern North America | found
589 / 925 Biopiracy | found
590 / 925 Natural Science and Indigenous Knowledge | found
Progress saved to Drive: 590
591 / 925 Indigenous religions | found
592 / 925 Science, colonialism, and indigenous peoples | not_found
593 / 925 African Indigenous Ecological Knowledge Systems | found
594 / 925 Protecting Indigenous Knowledge and Heritage | found
595 / 925 Participating in development | found
596 / 925 Global Biopiracy | not_found
597 / 925 Indigenous traditions and ecology | found
598 / 925 Red alert! | found
599 / 925 Indigenous Peoples Wisdom and Power | found
600 / 925 Indigenous Intergenerational Resilience | not_found
Progress saved to Drive: 600
601 / 925 Indigenous knowledge systems and sustainable development | found
602 / 925 Routledge Handbook of Indigenous Environmental Knowledge | found
603 / 925 Indigenous heritage and intellectual property | found
604 / 925 Indigenous Knowledge for Climate Change Assessment and Adaptation | not_found
605 / 925 Intellectual Property, Indigenous People and Their Knowledge | not_found
606 / 925 Voices from the forest | found
607 / 925 Ben tu sheng tai zhi shi yin lun = | found
608 / 925 Socio-Ecological Systems and Decoloniality | found
609 / 925 Sovereign subjects | not_found
610 / 925 Indigenous Land-Based Knowledge and Sustainability | found
Progress saved to Drive: 610
611 / 925 Land-based education | found
612 / 925 Indigenous food systems | found
613 / 925 The earth's blanket | found
614 / 925 People of the Himalayas | found
615 / 925 Tribal's and social inclusion | found
616 / 925 Catholicism's encounters with China | found
617 / 925 Nile River Basin | found
618 / 925 International encyclopedia of human geography | found
619 / 925 Report of the Royal Commission on Aboriginal Peoples | found
620 / 925 Religion and development in southern and central Africa | found
Progress saved to Drive: 620
621 / 925 THE MUSLIM DELUSION | found
622 / 925 A TOUR OF THE WORLD | not_found
623 / 925 Waldara Answers | not_found
624 / 925 Indigenous Environmental Knowledge | found
625 / 925 Indigenous Environmental Knowledge and its Transformations | found
626 / 925 Handbook of Indigenous Environmental Knowledge | found
627 / 925 Indigenous environmental knowledge and its transformations | found
628 / 925 Aboriginal environmental knowledge | not_found
629 / 925 Local Science Vs. Global Science | found
630 / 925 Twenty lessons in environmental sociology | not_found
Progress saved to Drive: 630
631 / 925 Cultural Studies and Environmentalism | found
632 / 925 Resilience Through Knowledge Co-Production | found
633 / 925 Indigenous knowledge and the environment in Africa and North America | found
634 / 925 Tending the Wild | not_found
635 / 925 Food and environmental security | found
636 / 925 The Need for Indigenous Knowledge in Environmental Impact Assessment | found
637 / 925 Indigenous Knowledge and Development | not_found
638 / 925 Intellectual property and aboriginal environmental knowledge | not_found
639 / 925 Landscape, process and power | not_found
640 / 925 The participation of indigenous peoples and the application of their environmental and ecological knowledge in the Arctic environmental protection strategy | not_found
Progress saved to Drive: 640
641 / 925 Cultural Studies And Environmentalism The Confluence Of Ecojustice Placebased Science Education And Indigenous Knowledge Systems | found
642 / 925 Cultural Hybridity and the Environment | found
643 / 925 Indigenous knowledge and biodiversity in Asia | not_found
644 / 925 Indigenous knowledge for biodiversity and development | found
645 / 925 Valuing local knowledge | found
646 / 925 Aboriginal Biocultural Knowledge in South-Eastern Australia | found
647 / 925 Traditional Forestrelated Knowledge Sustaining Communities Ecosystems And Biocultural Diversity | found
648 / 925 Traditional Forest-Related Knowledge | found
649 / 925 Biocultural diversity and indigenous ways of knowing | found
650 / 925 Bio-cultural diversity conserved by indigenous peoples & local communities-- examples & analysis | found
Progress saved to Drive: 650
651 / 925 Patrimonio biocultural, territorio y soc | found
652 / 925 Intellectual property rights for indigenous peoples | found
653 / 925 When Rights Embrace Responsibilities | found
654 / 925 Patrimonio biocultural, saberes y derechos de los pueblos originarios | found
655 / 925 Learning endogenous development | found
656 / 925 Conocimiento indígena contemporáneo y patrimonio biocultural en la Sierra Juárez de Oaxaca | not_found
657 / 925 El patrimonio biocultural de los pueblos indígenas de México | found
658 / 925 Genetic resources and traditional knowledge | found
659 / 925 Ethno-ornithology | found
660 / 925 Biodiversity and the law | found
Progress saved to Drive: 660
661 / 925 The profit of the earth | not_found
662 / 925 Patterns of commoning | found
663 / 925 Non-Humans in Amerindian South America | not_found
664 / 925 INTERNATIONAL RELATIONS IN UNCOMMON PLACES: INDIGENEITY, COSMOLOGY, AND THE LIMITS OF INTERNATIONAL.. | found
665 / 925 Civiltà indigene d'America | found
666 / 925 Spirits of Blood, Spirits of Breath | found
667 / 925 International Relations in Uncommon Places | not_found
668 / 925 Culturas visuales indígenas y las prácticas estéticas en las Américas desde la antigüedad hasta el presente | found
669 / 925 A Cree healer and his medicine bundle | found
670 / 925 La reconnaissance des peuples indigènes entre droit et politique | not_found
Progress saved to Drive: 670
671 / 925 Lo humano y lo divino | found
672 / 925 Sacred sites | found
673 / 925 New world, first nations | found
674 / 925 Arte indígena en tiempos del bicentenario | found
675 / 925 The snake with golden braids | found
676 / 925 The mystical chorus | found
677 / 925 Visión indigena | not_found
678 / 925 Aymara Indian Perspectives On Development In The Andes | not_found
679 / 925 Mesoamerica's classic heritage | not_found
680 / 925 Berkshire Encyclopedia of Sustainability Vol. 1 | found
Progress saved to Drive: 680
681 / 925 Paraíso abierto, jardines cerrados | not_found
682 / 925 Encuentro de dos | found
683 / 925 Inside cultures | found
684 / 925 Reclaiming indigenous voice and vision | found
685 / 925 Paradigm wars | found
686 / 925 The Sām- Ūpmā Mundhum Philosophy | found
687 / 925 Tecpán Guatemala | found
688 / 925 YACHAY AMARU | not_found
689 / 925 Framing the world | found
690 / 925 Thai folklore | not_found
Progress saved to Drive: 690
691 / 925 La joya del Inti | not_found
692 / 925 El pacto de la laguna | not_found
693 / 925 La miel de los cuatro vientos | not_found
694 / 925 Nina y la colada morada | not_found
695 / 925 La Leyenda de la Fanesca | not_found
696 / 925 Environmental studies | found
697 / 925 Indigenous Sacred Natural Sites and Spiritual Governance | not_found
698 / 925 Spiritual ecology | found
699 / 925 Sacred Forests of Asia | found
700 / 925 Indigenous religions | found
Progress saved to Drive: 700
701 / 925 Exploring the spiritualities of the world religions | found
702 / 925 Down to earth | found
703 / 925 Cultural and spiritual values of biodiversity | found
704 / 925 Yorro Yorro | found
705 / 925 Nature, space, and the sacred | found
706 / 925 Wild Animal Coloring Book | found
707 / 925 Worship and Wilderness | found
708 / 925 Living religions | found
709 / 925 Kinship | found
710 / 925 African traditions in the study of religion, diaspora and gendered societies | not_found
Progress saved to Drive: 710
711 / 925 Kinship | found
712 / 925 Penina uliuli | found
713 / 925 Heartsick for country | not_found
714 / 925 Diversity, culture, and counselling | found
715 / 925 Contemporary Issues in African Sciences and Science Education | found
716 / 925 Aboriginal history | found
717 / 925 Ancestors, spirits, and healing in Africa and Asia | found
718 / 925 Exploring the sacred | found
719 / 925 The strength perspective in social work practice | found
720 / 925 Meetings with mentors | found
Progress saved to Drive: 720
721 / 925 How Forests Think Toward An Anthropology Beyond The Human | found
722 / 925 How Forests Think | found
723 / 925 Humans and animals | found
724 / 925 Development and Local Knowledge | not_found
725 / 925 Biodiversity and Traditional Knowledge | not_found
726 / 925 The Oxford handbook on the United Nations | not_found
727 / 925 Kangaroo | found
728 / 925 Rethinking transitions | not_found
729 / 925 Science and stewardship to protect and sustain wilderness values | not_found
730 / 925 Native Americans and the environment | found
Progress saved to Drive: 730
731 / 925 The diversity of international law | found
732 / 925 Marble Mountain | not_found
733 / 925 A Latin American music reader | found
734 / 925 Indigenous and popular thinking in América | not_found
735 / 925 Indigenous people and archaeology | found
736 / 925 Structure, knowledge and representation in the Andes | not_found
737 / 925 A bibliography on the agriculture of the American Indians | found
738 / 925 Psychiatrist and traditional healers | found
739 / 925 Birthing Justice | found
740 / 925 Fundamentals of complementary and alternative medicine | found
Progress saved to Drive: 740
741 / 925 The Book of Yerba Mate | found
742 / 925 Faulkner and history | found
743 / 925 Examining social theory | found
744 / 925 Examining social theory | found
745 / 925 International HRM | found
746 / 925 The Routledge companion to media studies and digital humanities | not_found
747 / 925 Crossing Cultures | found
748 / 925 Witnesses to history | found
749 / 925 Indigenous Intellectuals | found
750 / 925 Mining Language | found
Progress saved to Drive: 750
751 / 925 Indigenous development in the Andes | found
752 / 925 Accessing biological resources | found
753 / 925 Carachula | not_found
754 / 925 Culture and Conservation | found
755 / 925 Culture and conservation | found
756 / 925 Andean cosmologies through time | found
757 / 925 At the Crossroads of the Earth and the Sky | not_found
758 / 925 Andean continuum cosmology | found
759 / 925 Andean Aesthetics and Anticolonial Resistance | not_found
760 / 925 Andean awakening | found
Progress saved to Drive: 760
761 / 925 Andean cartography | not_found
762 / 925 Yanantin and masintin in the Andean world | found
763 / 925 Andean/Incan mythology | found
764 / 925 Aquarian Age & the Andean Prophecy | not_found
765 / 925 Andean textile traditions | found
766 / 925 Moche | found
767 / 925 Handbook to life in the Inca World | found
768 / 925 Handbook to life in the ancient Inca world | found
769 / 925 Skyscapes | found
770 / 925 Pre-Columbian landscapes of creation and origin | not_found
Progress saved to Drive: 770
771 / 925 The occult life of things | found
772 / 925 Beyond the visible and the material | found
773 / 925 Amerindian cosmology | found
774 / 925 Amerindian Socio-Cosmologies Between the Andes, Amazonia and Mesoamerica | not_found
775 / 925 Dictionary of the Guyanese Amerindians | not_found
776 / 925 Knowing the Day Knowing the World | found
777 / 925 Caribbean religious history | found
778 / 925 Countering development | not_found
779 / 925 La protección del conocimiento tradicional en Colombia | found
780 / 925 Proceedings of the Pacific Council on Latin American Studies, 2002-2003 | found
Progress saved to Drive: 780
781 / 925 The sacred mountain of Colombia's Kogi Indians | found
782 / 925 Los Kogi | not_found
783 / 925 The Sacred Mountain of Colombia's Kogi Indians | found
784 / 925 Kogis | found
785 / 925 Territorio Kogi | found
786 / 925 Los Kogi de Sierra Nevada | found
787 / 925 Sistemas jurídicos paez, kogi, wayúu y tule | found
788 / 925 Saminashi | found
789 / 925 El solitario corazón comenzó a hablar | found
790 / 925 Introducción a las artes adivinatorias como prácticas mágico religiosas de caracter experimental entre los grupos indígenas serranos de la Sierra Nevada de Santa Marta, Colombia | not_found
Progress saved to Drive: 790
791 / 925 Estudios antropológicos | found
792 / 925 The evolution of social hierarchy in a Muisca chiefdom of the northern Andes of Colombia = | found
793 / 925 Los muiscas | found
794 / 925 Textiles de las culturas muisca y guane | not_found
795 / 925 Territorios y memorias culturales muiscas | not_found
796 / 925 Los muiscas | found
797 / 925 Eldorado Muisca | not_found
798 / 925 Los muiscas | not_found
799 / 925 Orfebrería prehispánica de Colombia, estilos tolima y muisca | not_found
800 / 925 El territorio de los muiscas a la llegada de los españoles | found
Progress saved to Drive: 800
801 / 925 Ornamentación calada en la orfebrería indígena precolombina (Muisca y Tolima) | found
802 / 925 Estado actual de los estudios etnologicos sobre los muiscas del Reino de Nueva Granada (Colombia) | found
803 / 925 Orfebrería prehispánica de Colombia : estilos tolima y muisca | found
804 / 925 Indios muiscas | found
805 / 925 Regional archaeology in the Muisca territory | found
806 / 925 Los muisca, un pueblo en reconstrucción | not_found
807 / 925 Documenting the emergence of chiefdoms in the Muisca territory | not_found
808 / 925 Los muiscas antes de la Conquista | found
809 / 925 Mensajes de la madre tierra en territorio muisca | found
810 / 925 El Dorado | not_found
Progress saved to Drive: 810
811 / 925 Les Muiscas | found
812 / 925 Cultura material de los muiscas | found
813 / 925 Los muiscas, pensamiento y realizaciones | found
814 / 925 La medicina en la cultura muisca | not_found
815 / 925 Instituciones jurídicas de la sociedad muisca | not_found
816 / 925 Sopó | found
817 / 925 Uque bique muisca | found
818 / 925 Los muiscas en los siglos XVI y XVII | found
819 / 925 Los chyquys de la nación muisca chibcha | found
820 / 925 Establecimiento de tipologías en la cerámica muisca | found
Progress saved to Drive: 820
821 / 925 Festejos muiscas en El Infiernito, Valle de Leyva | found
822 / 925 Los muiscas | found
823 / 925 Decolonial Philosophy of Indigenous Colombia | found
824 / 925 Los kamëntsá y el legado visual de la diócesis de Mocoa-Sibundoy | found
825 / 925 De conflictos, perdones y justicias | found
826 / 925 A reference grammar of Northern Embera languages | found
827 / 925 Proyecto Embera-Wera | not_found
828 / 925 Crisis humanitaria del pueblo Emberá | found
829 / 925 A dangerously toxic new frog (Phyllobates) used by Emberá Indians of western Colombia, with discussion of blowgun fabrication and dart poisoning | not_found
830 / 925 Zenú, emberá, wayú | found
Progress saved to Drive: 830
831 / 925 Bia 'Buma : el VIH/sida en los Emberá Chamí de Cristianía, Colombia. - 1. edición | found
832 / 925 Trua Wuandra | not_found
833 / 925 Emberas territorio y biodiversidad : estrategias de control en escenarios de conflicto | found
834 / 925 Cuéntelos bien como yo le conté | found
835 / 925 Ideas y prácticas ambientales del pueblo Embera del Chocó | found
836 / 925 Geografía humana de Colombia | found
837 / 925 Oralidad y escritura entre los embera-chamí de Risaralda | found
838 / 925 Prospección arqueológica del resguardo embera de Chajeradó, Murindo, Antioquia | not_found
839 / 925 Los embera y los cuna | found
840 / 925 Drúa-iujá | not_found
Progress saved to Drive: 840
841 / 925 Viaje y violencia | found
842 / 925 Población indígena en Antioquia | found
843 / 925 La tonina enamorada | found
844 / 925 Kipará | found
845 / 925 Kipara | not_found
846 / 925 Semejantes a los dioses | found
847 / 925 Colombia diversa | found
848 / 925 Las que cuidan el fogón | found
849 / 925 Deara, una ruta de acercamiento al espacio y a la arquitectura de los indígenas Embera y Waunana | found
850 / 925 Karagabí | found
Progress saved to Drive: 850
851 / 925 Simposio La recuperación de lenguas nativas como búsqueda de identidad étnica | not_found
852 / 925 El jaibaná en la encrucijada | found
853 / 925 Formación en derechos humanos y principios humanitarios del derecho internacional humanitario dirigido a pueblos indígenas | found
854 / 925 Chajeradó, el río de la caña flecha partida | found
855 / 925 La trama interétnica | found
856 / 925 Lenguas amerindias | not_found
857 / 925 Pueblos indígenas, Estados y derechos humanos | found
858 / 925 Gramática del páez o nasa yuwe | found
859 / 925 Autonomía en el Movimiento Indígena NASA a Partir de la Constitución Política de Colombia de 1991 | found
860 / 925 Entre la emancipación y la captura | found
Progress saved to Drive: 860
861 / 925 Lenguas Vivas de Colombia. Autodiagnóstico Sociolingüístico Volumen IV | found
862 / 925 Alvaro Ulcué, nasa pal | found
863 / 925 Proyecto Nasa | found
864 / 925 Öko-Kosmologie | found
865 / 925 Intercultural utopias | found
866 / 925 La guardia indígena nasa y el arte de la resistencia pacífica | found
867 / 925 Extractivismo minero en Colombia y América Latina | found
868 / 925 La fuerza del ombligo | found
869 / 925 La tierra contra la muerte | found
870 / 925 El pensamiento de la comunidad nasa yuwe | found
Progress saved to Drive: 870

/tmp/ipykernel_955/338118846.py:65: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  google_cache = pd.concat(

871 / 925 Kiwe Ten'za | not_found
872 / 925 Serie Rio de letras | found
873 / 925 Utopías interculturales | found
874 / 925 Construcción de micromundos | found
875 / 925 Los "teatros" de la memoria | found
876 / 925 Reconciliaciones y resistencias | not_found
877 / 925 El arco, el cuerpo y la seña | found
878 / 925 U' sxakwe sa'tkwe ena's umnxi | found
879 / 925 Experiencias de revitalización cultural y lingüística | found
880 / 925 De los saberes de la emancipación y de la dominación | found
Progress saved to Drive: 880
881 / 925 Pos-acuerdo y territorio en las comunidades indígenas, afro y campesinas en el norte del Cauca | found
882 / 925 Study of future world markets for agricultural aircraft | found
883 / 925 Mujeres indígenas haciendo, investigando y reescribiendo lo político en América Latina | found
884 / 925 Nosotros los Wayuu | found
885 / 925 Lo que saben los wayuu | found
886 / 925 Apalaanchi | found
887 / 925 El sabedor Wayuu | not_found
888 / 925 Censo binacional de la étnia wayuu, 1992 | found
889 / 925 El pueblo Wayuu | found
890 / 925 Las salinas de los Wayúu | found
Progress saved to Drive: 890
891 / 925 La masacre de Bahía Portete | found
892 / 925 Los Wayuu en la historia de América | found
893 / 925 Conceptos de la sexualidad Wayuu | not_found
894 / 925 Contribuciones al estudio de la etnomúsica y cultura wayuu | found
895 / 925 Material life and social metaphor | found
896 / 925 La cosmovisión wayuú a través de los textiles | found
897 / 925 Los esclavos wayuu de las haciendas del Zulia | found
898 / 925 La disputa y la palabra | found
899 / 925 Enfermedad y su tratamiento entre los wayuu | not_found
900 / 925 Matriarchale Spuren in Kolumbien | found
Progress saved to Drive: 900
901 / 925 Desde el desierto | found
902 / 925 Stratégies et Politiques de Reconnaissance et D'identité | found
903 / 925 Venezuela y Colombia | found
904 / 925 Cuando la sal se corrompe-- | not_found
905 / 925 Hijos de la lluvia y el desierto | found
906 / 925 Del monumento al pensamiento | found
907 / 925 Propuestas populares de política pública para la construcción de la paz | found
908 / 925 Desecrated land | found
909 / 925 Subregiones productivas del Caribe colombiano | http_503
910 / 925 Industria extractiva y derechos étnicos | not_found
Progress saved to Drive: 910
911 / 925 Decolonizing native histories | found
912 / 925 Inventing indigenous knowledge | found
913 / 925 Education, indigenous knowledge, and development in the global south | not_found
914 / 925 Native American Environmentalism | found
915 / 925 The river of life | found
916 / 925 Contemporary issues in California archaeology | not_found
917 / 925 Changing the Face of Mathematics | found
918 / 925 The Water Walker | found
919 / 925 Climate Change and Indigenous Peoples in the United States | found
920 / 925 Seed sovereignty, food security | found
Progress saved to Drive: 920
921 / 925 Our Ice Is Vanishing | found
922 / 925 Understanding child abuse and neglect | found
923 / 925 Proud to be Inuvialuit | found
924 / 925 The Human Planet | found
925 / 925 Treaty Occupationay Toxicology | found

In [1]:
google_test = pd.DataFrame(
    google_results
)

display(
    google_test[
        [
            "google_title",
            "google_authors",
            "description",
            "categories"
        ]
    ]
)

NameError: name 'pd' is not defined

In [ ]:
print(
    "Books found:",
    google_test["google_books_id"]
    .notna()
    .sum(),
    "out of",
    len(test_books)
)

print(
    "Descriptions found:",
    google_test["description"]
    .notna()
    .sum(),
    "out of",
    len(test_books)
)

Books found: 10 out of 10
Descriptions found: 8 out of 10

In [ ]:
GOOGLE_CACHE_FILE = (
    RAW_DATA / "google_books_enrichment.csv"
)

# Load previous progress if it exists
if GOOGLE_CACHE_FILE.exists():

    google_cache = pd.read_csv(
        GOOGLE_CACHE_FILE
    )

    completed_ids = set(
        google_cache["source_id"]
        .dropna()
        .astype(str)
    )

    print(
        "Previous results loaded:",
        len(google_cache)
    )

else:

    google_cache = pd.DataFrame()

    completed_ids = set()

    print("Starting new enrichment")


new_results = []

for index, row in books.iterrows():

    source_id = str(row["source_id"])

    # Skip books already processed
    if source_id in completed_ids:
        continue

    result = search_google_book(row)

    # Always save the source ID
    if result is None:

        result = {
            "source_id": source_id,
            "google_books_id": np.nan,
            "google_title": np.nan,
            "google_authors": np.nan,
            "description": np.nan,
            "categories": np.nan,
            "publisher": np.nan,
            "google_published_date": np.nan,
            "google_average_rating": np.nan,
            "google_ratings_count": np.nan
        }

    else:

        result["source_id"] = source_id

    new_results.append(result)

    print(
        f"{index + 1}/{len(books)}",
        row["title"]
    )

    # Save every 25 books
    if len(new_results) >= 25:

        batch = pd.DataFrame(
            new_results
        )

        google_cache = pd.concat(
            [google_cache, batch],
            ignore_index=True
        )

        google_cache.to_csv(
            GOOGLE_CACHE_FILE,
            index=False
        )

        new_results = []

        print(
            "Progress saved:",
            len(google_cache),
            "books"
        )

    time.sleep(1)


# Save the final incomplete batch
if new_results:

    batch = pd.DataFrame(
        new_results
    )

    google_cache = pd.concat(
        [google_cache, batch],
        ignore_index=True
    )

    google_cache.to_csv(
        GOOGLE_CACHE_FILE,
        index=False
    )


print("\nEnrichment finished")

print(
    "Books processed:",
    len(google_cache)
)

Starting new enrichment
1/925 The ecology of human development
2/925 People and nature
3/925 The green imperative
4/925 Design with nature
5/925 The death of nature: women, ecology, and the scientific revolution
6/925 Human geography
7/925 Galen's Prophecy
8/925 Man's responsibility for nature
9/925 Ecological Transition
10/925 Biomimicry
11/925 Sex, ecology, spirituality
12/925 Team human
13/925 Ecology and equity
14/925 Human Ecology
15/925 Understanding Human Ecology
16/925 Ecological revolutions
17/925 Human ecology
18/925 Ecology
19/925 Man, nature, and ecology
20/925 Human ecology
21/925 Environmental philosophy
22/925 Sacred ecology
23/925 Human dimensions of ecological restoration
24/925 The forest and the sea
25/925 Man's nature and nature's man
Progress saved: 25 books
26/925 Being Ecological
27/925 Human-nature interactions in the anthropocene
28/925 Last Child in the Woods
29/925 Islands of Abandonment
30/925 Natural capital and human economic survival
31/925 Environmental Humanities and Theologies
32/925 Routledge Handbook of the Digital Environmental Humanities
33/925 Environmental science
34/925 Environmental Human Rights
35/925 Environmental Human Rights
36/925 The Environmental Humanities
37/925 Introduction to the Environmental Humanities
38/925 Global Ecologies and the Environmental Humanities
39/925 Disability Studies and the Environmental Humanities
40/925 Environmental Science
41/925 Routledge Companion to the Environmental Humanities
42/925 Environmental Humanities and the Uncanny
43/925 Environmental Humanities
44/925 Epistemic Justice, Mindfulness, and the Environmental Humanities
45/925 Environmental Human Rights and Climate Change
46/925 Avatar and Nature Spirituality

                Environmental Humanities
47/925 Religion, Narrative, and the Environmental Humanities
48/925 Environmental Humanities in the New Himalayas
49/925 Cambridge Companion to Environmental Humanities
50/925 Environmental Humanities of Extraction in Africa
Progress saved: 50 books
51/925 Grounding Education in Environmental Humanities
52/925 Environmental science
53/925 Environmental science
Status 429 for Eighteenth-Century Environmental Humanities
54/925 Eighteenth-Century Environmental Humanities
Status 429 for Ecological Exile
55/925 Ecological Exile
Status 429 for Environmental science
56/925 Environmental science
Status 429 for Bloomsbury Handbook to the Medical-Environmental Humanities
57/925 Bloomsbury Handbook to the Medical-Environmental Humanities
Status 429 for An Approach to environmental psychology
58/925 An Approach to environmental psychology
Status 429 for Rethinking Invasion Ecologies from the Environmental Humanities
59/925 Rethinking Invasion Ecologies from the Environmental Humanities
Status 429 for Environmental Human Rights in the Anthropocene
60/925 Environmental Human Rights in the Anthropocene
Status 429 for More Than Human
61/925 More Than Human
Status 429 for The spell of the sensuous
62/925 The spell of the sensuous
63/925 No more than human
64/925 More Than Human
Status 429 for Participatory Research in More-Than-Human Worlds
65/925 Participatory Research in More-Than-Human Worlds
Status 429 for More than human
66/925 More than human
Status 429 for More Than Human
67/925 More Than Human
Status 429 for Injecting Bodies in More-Than-human Worlds
68/925 Injecting Bodies in More-Than-human Worlds
Status 429 for Data Selves
69/925 Data Selves
Status 429 for Walking Methodologies in a More-Than-human World
70/925 Walking Methodologies in a More-Than-human World
71/925 Matters of Care
Status 429 for Healthy Urban Environments
72/925 Healthy Urban Environments
73/925 Humans, Animals and Biopolitics
Status 429 for Radical Environmentalism
74/925 Radical Environmentalism
Status 429 for Designing More-Than-Human Smart Cities
75/925 Designing More-Than-Human Smart Cities
Progress saved: 75 books
Status 429 for I Love My Dog More Than Humans
76/925 I Love My Dog More Than Humans
Status 429 for More Than Human
77/925 More Than Human
Status 429 for More-Than-Human Aging
78/925 More-Than-Human Aging
Status 429 for Anthropocene Psychology
79/925 Anthropocene Psychology
Status 429 for Biopolitics of the More-Than-Human
80/925 Biopolitics of the More-Than-Human
Status 429 for More-than-Human Sociology
81/925 More-than-Human Sociology
82/925 More-Than-Human Aesthetics
Status 429 for More-Than-Human Choreography
83/925 More-Than-Human Choreography
Status 429 for The Spell of the Sensuous
84/925 The Spell of the Sensuous
Status 429 for City Is More Than Human
85/925 City Is More Than Human
Status 429 for Digital Ecologies
86/925 Digital Ecologies
Status 429 for More-Than-Human Design in Practice
87/925 More-Than-Human Design in Practice
Status 429 for Design for More-Than-Human Futures
88/925 Design for More-Than-Human Futures
Status 429 for Mammoth Books Presents More Than Human
89/925 Mammoth Books Presents More Than Human
Status 429 for Ecofeminism
90/925 Ecofeminism
Status 429 for Ecofeminism
91/925 Ecofeminism
Status 429 for Ecofeminism
92/925 Ecofeminism
Status 429 for Healing the Wounds
93/925 Healing the Wounds
Status 429 for Ecofeminism and Systems Thinking
94/925 Ecofeminism and Systems Thinking
Status 429 for Reweaving The World
95/925 Reweaving The World
96/925 Ecofeminism
Status 429 for Ecofeminism And The Sacred
97/925 Ecofeminism And The Sacred
Status 429 for Ecofeminism as politics
98/925 Ecofeminism as politics
Status 429 for What is ecofeminism?
99/925 What is ecofeminism?
100/925 Ecofeminism
Progress saved: 100 books
Status 429 for Ecofeminism revisited
101/925 Ecofeminism revisited
Status 429 for Ecofeminism and globalization
102/925 Ecofeminism and globalization
Status 429 for Critical Ecofeminism
103/925 Critical Ecofeminism
Status 429 for Contemporary Perspectives on Ecofeminism
104/925 Contemporary Perspectives on Ecofeminism
Status 429 for Literature and Ecofeminism
105/925 Literature and Ecofeminism
Status 429 for Ecofeminism
106/925 Ecofeminism
Status 429 for Longing for running water
107/925 Longing for running water
Status 429 for Ecofeminism and the Indian Novel
108/925 Ecofeminism and the Indian Novel
109/925 D. H. Lawrence, Ecofeminism and Nature
110/925 Changing Nature of Eco/Feminism
Status 429 for Place and Postcolonial Ecofeminism
111/925 Place and Postcolonial Ecofeminism
Status 429 for Ecofeminism on the Edge
112/925 Ecofeminism on the Edge
Status 429 for Routledge Handbook of Ecofeminism and Literature
113/925 Routledge Handbook of Ecofeminism and Literature
Status 429 for Ecofeminism reader
114/925 Ecofeminism reader
Status 429 for Ecofeminism in Dialogue
115/925 Ecofeminism in Dialogue
Status 429 for Ecofeminism
116/925 Ecofeminism
Status 429 for What is ecofeminism anyway?
117/925 What is ecofeminism anyway?
Status 429 for Queer Ecofeminism
118/925 Queer Ecofeminism
Status 429 for Deep Ecology & Anarchism
119/925 Deep Ecology & Anarchism
Status 429 for Deep ecology
120/925 Deep ecology
Status 429 for THE DEEP ECOLOGICAL MOVEMENT: SOME PHILOSOPHICAL ASPECTS
121/925 THE DEEP ECOLOGICAL MOVEMENT: SOME PHILOSOPHICAL ASPECTS
Status 429 for Deep Ecology for the 21st century
122/925 Deep Ecology for the 21st century
Status 429 for Deep Ecology Movement
123/925 Deep Ecology Movement
Status 429 for Eco-socialism
124/925 Eco-socialism
Status 429 for DEEP ECOLOGY
125/925 DEEP ECOLOGY
Progress saved: 125 books
Status 429 for Deep Ecology
126/925 Deep Ecology
Status 429 for Spinoza and Deep Ecology
127/925 Spinoza and Deep Ecology
Status 429 for Gaia Psyche and Deep Ecology
128/925 Gaia Psyche and Deep Ecology
Status 429 for Buddhism and Deep Ecology
129/925 Buddhism and Deep Ecology
Status 429 for How deep is deep ecology?
130/925 How deep is deep ecology?
Status 429 for Deep Ecology
131/925 Deep Ecology
Status 429 for Buddhism and Deep Ecology
132/925 Buddhism and Deep Ecology
133/925 Deep Ecology, Business Ethics and Personal Responsibility
Status 429 for Toward a naturalistic political theory
134/925 Toward a naturalistic political theory
Status 429 for Dark night, early dawn
135/925 Dark night, early dawn
Status 429 for Spinoza and the deep ecology movement
136/925 Spinoza and the deep ecology movement
Status 429 for Deep ecology
137/925 Deep ecology
Status 429 for Discussion course on exploring deep ecology
138/925 Discussion course on exploring deep ecology
Status 429 for Deep Ecology
139/925 Deep Ecology
Status 429 for Deep ecology
140/925 Deep ecology
Status 429 for Beneath the surface
141/925 Beneath the surface
Status 429 for Approaching deep ecology
142/925 Approaching deep ecology
Status 429 for Regarding nature
143/925 Regarding nature
Status 429 for Living Deep Ecology
144/925 Living Deep Ecology
Status 429 for The Culture of Extinction
145/925 The Culture of Extinction
Status 429 for POSTMODERN ENVIRONMENTALISM: A CRITIQUE OF DEEP ECOLOGY
146/925 POSTMODERN ENVIRONMENTALISM: A CRITIQUE OF DEEP ECOLOGY
Status 429 for Gandhi and deep ecology
147/925 Gandhi and deep ecology
Status 429 for A critique of deep ecology
148/925 A critique of deep ecology
Status 429 for Building for Life
149/925 Building for Life
Status 429 for Loneliness
150/925 Loneliness
Progress saved: 150 books
Status 429 for Social Intelligence
151/925 Social Intelligence
Status 429 for The good in nature and humanity
152/925 The good in nature and humanity
153/925 Place-based education
Status 429 for Connected Lives
154/925 Connected Lives
Status 429 for Nature and culture
155/925 Nature and culture
Status 429 for Wittgenstein
156/925 Wittgenstein
Status 429 for Survival of the Sickest
157/925 Survival of the Sickest
Status 429 for Natural learning for a connected world
158/925 Natural learning for a connected world
Status 429 for Human transit
159/925 Human transit
Status 429 for Urbanizing Nature
160/925 Urbanizing Nature
Status 429 for Consciousness Connection
161/925 Consciousness Connection
Status 429 for The good in nature and humanity : connecting science, religion, and spirituality with the natural world
162/925 The good in nature and humanity : connecting science, religion, and spirituality with the natural world
Status 429 for Get Outside!
163/925 Get Outside!
Status 429 for Lexicon medicum
164/925 Lexicon medicum
Status 429 for Literature. The Human Experience, Reading and Writing--Twelfth Edition
165/925 Literature. The Human Experience, Reading and Writing--Twelfth Edition
Status 429 for Humanity's Connection to the Natural World
166/925 Humanity's Connection to the Natural World
Status 429 for Planning connections
167/925 Planning connections
Status 429 for The primordial bond
168/925 The primordial bond
Status 429 for Awakening to Nature
169/925 Awakening to Nature
Status 429 for The primordial bond
170/925 The primordial bond
Status 429 for Earth signs
171/925 Earth signs
Status 429 for The voice of the infinite in the small
172/925 The voice of the infinite in the small
Status 429 for Connection to Nature, Deep Ecology, and Conservation Social Science
173/925 Connection to Nature, Deep Ecology, and Conservation Social Science
Status 429 for Human Natural Form : a Close Connection with Intellect
174/925 Human Natural Form : a Close Connection with Intellect
Status 429 for Connect Access Card for Personality Psychology
175/925 Connect Access Card for Personality Psychology
Progress saved: 175 books
Status 429 for Earth changes and the human-cosmic connection
176/925 Earth changes and the human-cosmic connection
Status 429 for Patanjali yoga sutras
177/925 Patanjali yoga sutras
Status 429 for Yogasūtra
178/925 Yogasūtra
Status 429 for Yoga sutras
179/925 Yoga sutras
Status 429 for Light on the Yoga Sutras of Patanjali
180/925 Light on the Yoga Sutras of Patanjali
Status 429 for Patanjali Yoga Sutras
181/925 Patanjali Yoga Sutras
Status 429 for Yoga-Sutra
182/925 Yoga-Sutra
183/925 The Yoga Sutras of Patanjali
Status 429 for Yoga
184/925 Yoga
Status 429 for The yoga sutras of Patanjali
185/925 The yoga sutras of Patanjali
Status 429 for How to know God
186/925 How to know God
Status 429 for Yoga-sutras
187/925 Yoga-sutras
Status 429 for The Yoga-Sútra of Patañjali
188/925 The Yoga-Sútra of Patañjali
189/925 Tree of Yoga
Status 429 for Yoga Sutras of Patanjali
190/925 Yoga Sutras of Patanjali
191/925 Yoga Sastra
Status 429 for Yoga Sutras of Patanjali
192/925 Yoga Sutras of Patanjali
Status 429 for Yoga, the art of integration
193/925 Yoga, the art of integration
Status 429 for Patanjali's Yoga Sutras
194/925 Patanjali's Yoga Sutras
Status 429 for The Yoga Sutras of Patanjali
195/925 The Yoga Sutras of Patanjali
Status 429 for The Yoga sutras of Patañjali
196/925 The Yoga sutras of Patañjali
Status 429 for Yoga Sutras of Patanjali
197/925 Yoga Sutras of Patanjali
Status 429 for The Yoga Sutras Of Patanjali
198/925 The Yoga Sutras Of Patanjali
Status 429 for Patanjali Yoga Sutras
199/925 Patanjali Yoga Sutras
Status 429 for The Yoga sutras of Patanjali
200/925 The Yoga sutras of Patanjali
Progress saved: 200 books
Status 429 for Yoga sutras of Patanjali
201/925 Yoga sutras of Patanjali
Status 429 for Yogasūtra. English
202/925 Yogasūtra. English
203/925 Beyond The Siddhis
Status 429 for Patanjali's Yoga Sutras
204/925 Patanjali's Yoga Sutras
Status 429 for Yoga Sutras of Patanjali
205/925 Yoga Sutras of Patanjali
Status 429 for The Holy Vedas ; Rig Veda, Yajur Veda, Sama Veda, Atharva Veda
206/925 The Holy Vedas ; Rig Veda, Yajur Veda, Sama Veda, Atharva Veda
Status 429 for Rig-Veda
207/925 Rig-Veda
Status 429 for The Vedas
208/925 The Vedas
Status 429 for Atharva vēda
209/925 Atharva vēda
Status 429 for Der Rig-Veda, Part IV, Index
210/925 Der Rig-Veda, Part IV, Index
Status 429 for Hymns to the mystic fire
211/925 Hymns to the mystic fire
Status 429 for Rig-Veda Sanhita
212/925 Rig-Veda Sanhita
Status 429 for Rig-veda
213/925 Rig-veda
Status 429 for The religion and philosophy of the Veda and Upanishads
214/925 The religion and philosophy of the Veda and Upanishads
Status 429 for Vedas
215/925 Vedas
Status 429 for Building architecture of Sthāpatya Veda
216/925 Building architecture of Sthāpatya Veda
Status 429 for Vedic hymns
217/925 Vedic hymns
Status 429 for The religion of the Veda =
218/925 The religion of the Veda =
Status 429 for The Vēdas
219/925 The Vēdas
Status 429 for Nasty Nature (Horrible Science)
220/925 Nasty Nature (Horrible Science)
Status 429 for The Holy Vedas
221/925 The Holy Vedas
Status 429 for The Rig Veda
222/925 The Rig Veda
Status 429 for Human Physiology
223/925 Human Physiology
Status 429 for The Atharvaveda
224/925 The Atharvaveda
Status 429 for The Rig Veda
225/925 The Rig Veda
Progress saved: 225 books
Status 429 for Atharva-Veda-Saṁhitā
226/925 Atharva-Veda-Saṁhitā
Status 429 for The Vedas and Upanishads for Children
227/925 The Vedas and Upanishads for Children
Status 429 for Sanskrit Grammar
228/925 Sanskrit Grammar
Status 429 for Rig Veda
229/925 Rig Veda
Status 429 for Sciences in the Vedas
230/925 Sciences in the Vedas
Status 429 for The Vedas
231/925 The Vedas
Status 429 for Rig Veda
232/925 Rig Veda
Status 429 for The Holy Vedas
233/925 The Holy Vedas
Status 429 for Rig-veda, oder, Die heiligen lieder der Brahmanen
234/925 Rig-veda, oder, Die heiligen lieder der Brahmanen
Status 429 for Sam-Veda Sanhita
235/925 Sam-Veda Sanhita
Status 429 for The Upanishads
236/925 The Upanishads
Status 429 for Upanishads
237/925 Upanishads
238/925 The Upanishads. Tr. by F.M. Müller
Status 429 for Eight Upanishads
239/925 Eight Upanishads
Status 429 for Ghar Ghar Upanishad
240/925 Ghar Ghar Upanishad
Status 429 for The Upanishads
241/925 The Upanishads
Status 429 for Twenty-Eight Upanishads (Îsha & Others).
242/925 Twenty-Eight Upanishads (Îsha & Others).
Status 429 for Philosophie der Upanishad's
243/925 Philosophie der Upanishad's
Status 429 for Ishavasya Upanishad
244/925 Ishavasya Upanishad
Status 429 for Mundaka Upanishad
245/925 Mundaka Upanishad
Status 429 for The Upanishads
246/925 The Upanishads
Status 429 for Niralamba Upanishad
247/925 Niralamba Upanishad
Status 429 for Niralamba Upanishad (Vol 1)
248/925 Niralamba Upanishad (Vol 1)
249/925 The Upanishads
Status 429 for The Upanishads
250/925 The Upanishads
Progress saved: 250 books
Status 429 for Mandukya Upanishad
251/925 Mandukya Upanishad
Status 429 for The Upanishads
252/925 The Upanishads
Status 429 for Upanishads
253/925 Upanishads
Status 429 for The Upanishads
254/925 The Upanishads
Status 429 for The Upanishads
255/925 The Upanishads
256/925 Upaniṣads
Status 429 for Dialogue with death
257/925 Dialogue with death
Status 429 for The Upanishads
258/925 The Upanishads
Status 429 for Upanishads
259/925 Upanishads
Status 429 for Upanishads
260/925 Upanishads
Status 429 for The Upanishads
261/925 The Upanishads
Status 429 for Upanishads
262/925 Upanishads
Status 429 for Bhagavad-Gita
263/925 Bhagavad-Gita
Status 429 for The Bhagavad gita
264/925 The Bhagavad gita
Status 429 for Shrimad Bhagvat
265/925 Shrimad Bhagvat
Status 429 for The Bhagavad-Gita
266/925 The Bhagavad-Gita
Status 429 for Bhagavad Gita
267/925 Bhagavad Gita
Status 429 for Bhagavad-Gita As It Is
268/925 Bhagavad-Gita As It Is
Status 429 for The Bhagavad Gita
269/925 The Bhagavad Gita
Status 429 for भगवद्गीता
270/925 भगवद्गीता
Status 429 for Paths to god
271/925 Paths to god
Status 429 for Bhagavad Gita
272/925 Bhagavad Gita
Status 429 for Bhagavad Gītā
273/925 Bhagavad Gītā
Status 429 for The Bhagavad Gita
274/925 The Bhagavad Gita
Status 429 for Shrimad bhagvad gita
275/925 Shrimad bhagvad gita
Progress saved: 275 books
Status 429 for The Bhagavad Gita
276/925 The Bhagavad Gita
Status 429 for Srīmad Bhagavad-gītā
277/925 Srīmad Bhagavad-gītā
Status 429 for Bhagavad Gita
278/925 Bhagavad Gita
Status 429 for Bhagavad Gītā
279/925 Bhagavad Gītā
Status 429 for The Bhagavad-gita
280/925 The Bhagavad-gita
Status 429 for Illuminations from the Bhagavad-gĩtã
281/925 Illuminations from the Bhagavad-gĩtã
Status 429 for Bhagavad Gita (Harvard Oriental)
282/925 Bhagavad Gita (Harvard Oriental)
Status 429 for Bhagavad Gita
283/925 Bhagavad Gita
284/925 The Bhagavad-Gita
Status 429 for Bhagavad Gita
285/925 Bhagavad Gita
Status 429 for Introduction to Bhagavad-gita
286/925 Introduction to Bhagavad-gita
Status 429 for Bhagavad-Gita
287/925 Bhagavad-Gita
Status 429 for Songs of the soul
288/925 Songs of the soul
Status 429 for The Bhagavad Gita
289/925 The Bhagavad Gita
Status 429 for Perennial psychology of the Bhagavad Gita
290/925 Perennial psychology of the Bhagavad Gita
Status 429 for A Treatise on the Yoga Philosophy
291/925 A Treatise on the Yoga Philosophy
Status 429 for Yoga philosophy
292/925 Yoga philosophy
Status 429 for The Inner Tradition of Yoga
293/925 The Inner Tradition of Yoga
Status 429 for Yoga philosophy
294/925 Yoga philosophy
Status 429 for Pantajali's Yoga Philosophy
295/925 Pantajali's Yoga Philosophy
Status 429 for The Yoga Tradition
296/925 The Yoga Tradition
Status 429 for Sūtras, Stories and Yoga Philosophy
297/925 Sūtras, Stories and Yoga Philosophy
Status 429 for Introduction to Yoga Philosophy
298/925 Introduction to Yoga Philosophy
Status 429 for The Eight Limbs of Yoga
299/925 The Eight Limbs of Yoga
Status 429 for I-God
300/925 I-God
Progress saved: 300 books
Status 429 for Higher Psychical Development (Yoga Philosophy) an Outline of the Secret Hindu Teachings
301/925 Higher Psychical Development (Yoga Philosophy) an Outline of the Secret Hindu Teachings
Status 429 for Yoga Philosophy
302/925 Yoga Philosophy
Status 429 for Introduction to the Yoga Philosophy
303/925 Introduction to the Yoga Philosophy
Status 429 for Yoga Philosophy and Practice
304/925 Yoga Philosophy and Practice
Status 429 for A Treatise on the Yoga Philosophy
305/925 A Treatise on the Yoga Philosophy
Status 429 for A Treatise On The Yoga Philosophy / By N.c. Paul
306/925 A Treatise On The Yoga Philosophy / By N.c. Paul
Status 429 for Yoga Sastra : The Yoga Sutras of Patenjali Examined

In [ ]:
print("Total attempted:", len(google_cache))

print(
    "Successful Google matches:",
    google_cache["google_books_id"].notna().sum()
)

print(
    "Descriptions found:",
    google_cache["description"].notna().sum()
)

print(
    "Failed or unavailable:",
    google_cache["google_books_id"].isna().sum()
)

Total attempted: 925
Successful Google matches: 80
Descriptions found: 65
Failed or unavailable: 845

## 9. Univariate exploration

In [ ]:
plt.figure(figsize=(8, 5))
books["average_rating"].dropna().hist(bins=15)
plt.title("Distribution of average ratings")
plt.xlabel("Average rating")
plt.ylabel("Number of books")
plt.show()

plt.figure(figsize=(8, 5))
books["subject_count"].hist(bins=20)
plt.title("Distribution of subject count")
plt.xlabel("Number of subjects")
plt.ylabel("Number of books")
plt.show()

In [ ]:
google_cache["status"] = np.where(
    google_cache["google_books_id"].notna(),
    "found",
    "needs_retry"
)

print(
    google_cache["status"].value_counts()
)

status
needs_retry    845
found           80
Name: count, dtype: int64

In [ ]:
google_cache.to_csv(
    GOOGLE_CACHE_FILE,
    index=False
)

In [ ]:
successful_ids = set(
    google_cache.loc[
        google_cache["status"] == "found",
        "source_id"
    ].astype(str)
)

retry_books = books[
    ~books["source_id"]
    .astype(str)
    .isin(successful_ids)
].copy()

print(
    "Books remaining:",
    len(retry_books)
)

Books remaining: 845

In [4]:
import pandas as pd
import numpy as np
import requests
import time

from pathlib import Path
from google.colab import userdata

GOOGLE_BOOKS_API_KEY = userdata.get(
    "API_key_books"
)

In [5]:
from pathlib import Path

list(Path("/content").rglob("google_books_enrichment.csv"))

[]

In [6]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

In [7]:
from pathlib import Path

DRIVE_PROJECT = Path(
    "/content/drive/MyDrive/kinship_library"
)

RAW_DATA = DRIVE_PROJECT / "data" / "raw"
PROCESSED_DATA = DRIVE_PROJECT / "data" / "processed"

RAW_DATA.mkdir(
    parents=True,
    exist_ok=True
)

PROCESSED_DATA.mkdir(
    parents=True,
    exist_ok=True
)

print("Project folder:", DRIVE_PROJECT)

Project folder: /content/drive/MyDrive/kinship_library

In [8]:
list(
    Path("/content/drive/MyDrive").rglob(
        "open_library_books.csv"
    )
)

[]

## 10. Outlier check

We use the IQR rule to flag unusual values. Flagging an outlier does not mean deleting it.

In [ ]:
q1 = books["subject_count"].quantile(0.25)
q3 = books["subject_count"].quantile(0.75)
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

subject_outliers = books[
    (books["subject_count"] < lower_bound)
    | (books["subject_count"] > upper_bound)
]

print("LCV for IQR inspection:", lower_bound)
print("UCV for IQR inspection:", upper_bound)
print("Outliers:", len(subject_outliers))

plt.figure(figsize=(8, 4))
plt.boxplot(books["subject_count"].dropna(), vert=False)
plt.title("Subject count outlier check")
plt.xlabel("Number of subjects")
plt.show()

## 11. Probability

Estimate the probability that a randomly selected record in our collected sample has at least five subjects.

This probability describes our sample, not the entire population of books.

In [ ]:
has_rich_subject_metadata = books["subject_count"] >= 5
probability_rich_metadata = has_rich_subject_metadata.mean()

print(
    "Estimated probability:",
    round(probability_rich_metadata, 3)
)

## 12. Bivariate exploration and correlation

In [ ]:
correlation_data = books[
    ["average_rating", "ratings_count", "published_year", "subject_count"]
].copy()

correlation_matrix = correlation_data.corr(numeric_only=True)
correlation_matrix

## 13. Normal distribution check for ratings

Null hypothesis: average ratings are compatible with a normal distribution.

Alternative hypothesis: average ratings are not compatible with a normal distribution.

Alpha level: 0.05.

In [ ]:
rating_values = books["average_rating"].dropna()

if len(rating_values) >= 3:
    sample = rating_values.sample(
        min(len(rating_values), 500),
        random_state=RANDOM_STATE
    )

    statistic, p_value = stats.shapiro(sample)

    print("Test statistic:", round(statistic, 4))
    print("P value:", round(p_value, 4))
    print("Alpha:", 0.05)

    if p_value < 0.05:
        print("Decision: reject the null hypothesis")
    else:
        print("Decision: fail to reject the null hypothesis")
else:
    print("Not enough rating observations")

## 14. Bivariate hypothesis test with rejection regions

Question: Is mean subject count different between the humans and nature collection and Yoga philosophy collection?

Null hypothesis: the two population means are equal.

Alternative hypothesis: the two population means are different.

Test: two sided Welch t test.

Alpha: 0.05.

In [ ]:
group_a = books.loc[
    books["collection_theme"] == "humans_and_nature",
    "subject_count"
].dropna()

group_b = books.loc[
    books["collection_theme"] == "yoga_philosophy",
    "subject_count"
].dropna()

alpha = 0.05

if len(group_a) >= 2 and len(group_b) >= 2:

    test_statistic, p_value = stats.ttest_ind(
        group_a,
        group_b,
        equal_var=False
    )

    var_a = group_a.var(ddof=1)
    var_b = group_b.var(ddof=1)
    n_a = len(group_a)
    n_b = len(group_b)

    df_num = (var_a / n_a + var_b / n_b) ** 2
    df_den = (
        ((var_a / n_a) ** 2) / (n_a - 1)
        + ((var_b / n_b) ** 2) / (n_b - 1)
    )
    degrees_freedom = df_num / df_den

    lcv = stats.t.ppf(alpha / 2, degrees_freedom)
    ucv = stats.t.ppf(1 - alpha / 2, degrees_freedom)

    print("Test statistic:", round(test_statistic, 4))
    print("P value:", round(p_value, 4))
    print("Alpha:", alpha)
    print("LCV:", round(lcv, 4))
    print("UCV:", round(ucv, 4))

    if p_value < alpha:
        print("Decision: reject the null hypothesis")
    else:
        print("Decision: fail to reject the null hypothesis")

    x = np.linspace(
        stats.t.ppf(0.001, degrees_freedom),
        stats.t.ppf(0.999, degrees_freedom),
        500
    )
    y = stats.t.pdf(x, degrees_freedom)

    plt.figure(figsize=(9, 5))
    plt.plot(x, y)

    plt.fill_between(
        x[x <= lcv],
        stats.t.pdf(x[x <= lcv], degrees_freedom),
        alpha=0.3
    )

    plt.fill_between(
        x[x >= ucv],
        stats.t.pdf(x[x >= ucv], degrees_freedom),
        alpha=0.3
    )

    plt.axvline(lcv, linestyle="--", label="LCV")
    plt.axvline(ucv, linestyle="--", label="UCV")
    plt.axvline(test_statistic, label="Test statistic")

    plt.title("Welch t test with rejection regions")
    plt.xlabel("t value")
    plt.ylabel("Probability density")
    plt.legend()
    plt.show()

else:
    print("Not enough observations for the test")

## 15. Save the clean catalogue

The next notebook will use this file. This separation means we do not need to call the APIs every time we experiment with NLP.

In [ ]:
CLEAN_FILE = PROCESSED_DATA / "books_clean.csv"

books.to_csv(CLEAN_FILE, index=False)

print("Saved:", CLEAN_FILE)
print("Rows:", len(books))